[build]
  command = "npm run build:prod"
  publish = "dist"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ./src/"

[dev]
  command = "npm run dev"
  port = 5173
  publish = "dist"

# Ensure assets are served with correct MIME types
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "/assets/*.css"
  [headers.values]
    Content-Type = "text/css; charset=utf-8"

[[headers]]
  for = "/assets/*.svg"
  [headers.values]
    Content-Type = "image/svg+xml"

# General security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "index, follow"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https://raw.githubusercontent.com; font-src 'self' data:; connect-src 'self' https://kefcxvcbpadksfizrckw.supabase.co https://beta.pokeapi.co https://pokeapi.co;"
    Access-Control-Allow-Origin = "*"

# Make sure assets are never redirected
[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200
  force = false

# Redirect www to non-www version
[[redirects]]
  from = "https://www.react-pokedex.netlify.app/*"
  to = "https://react-pokedex.netlify.app/:splat"
  status = 301
  force = true

# Handle SPA routing for everything else
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# Enable brotli compression for better performance
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true
