-- Server-owned competitive sets for VS random teams. Keeping the roll inside the
-- database prevents clients from disguising arbitrary builds as curated ones.

CREATE TABLE IF NOT EXISTS public.vs_competitive_builds (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pokemon_id INTEGER NOT NULL REFERENCES public.pokemon(id) ON DELETE CASCADE,
  format TEXT NOT NULL,
  build_name TEXT NOT NULL,
  build JSONB NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  UNIQUE (pokemon_id, format, build_name)
);

ALTER TABLE public.vs_competitive_builds ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.vs_competitive_builds FROM PUBLIC, anon, authenticated;

-- BEGIN GENERATED SMOGON POOL
INSERT INTO public.vs_competitive_builds (pokemon_id, format, build_name, build)
VALUES
  (3, 'gen9zu', 'Defensive', '{"ability":"Overgrow","moves":["Giga Drain","Sludge Bomb","Knock Off","Synthesis"],"item":"Leftovers","nature":"Bold","evs":{"hp":252,"atk":0,"def":168,"spa":0,"spd":0,"spe":88},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Water"}'::JSONB),
  (6, 'gen9pu', 'Sun Wallbreaker', '{"ability":"Solar Power","moves":["Weather Ball","Solar Beam","Focus Blast","Flamethrower"],"item":"Choice Specs","nature":"Timid","evs":{"hp":0,"atk":0,"def":4,"spa":252,"spd":0,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Fire"}'::JSONB),
  (9, 'gen9uu', 'Shell Smash', '{"ability":"Torrent","moves":["Shell Smash","Surf","Ice Beam","Tera Blast"],"item":"White Herb","nature":"Modest","evs":{"hp":0,"atk":0,"def":0,"spa":252,"spd":4,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Electric"}'::JSONB),
  (28, 'gen9zu', 'Rapid Spin', '{"ability":"Sand Rush","moves":["Rapid Spin","Earthquake","Knock Off","Stealth Rock"],"item":"Heavy-Duty Boots","nature":"Impish","evs":{"hp":252,"atk":0,"def":252,"spa":0,"spd":4,"spe":0},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Ghost"}'::JSONB),
  (36, 'gen9ou', 'Utility', '{"ability":"Magic Guard","moves":["Stealth Rock","Moonblast","Moonlight","Thunder Wave"],"item":"Leftovers","nature":"Bold","evs":{"hp":252,"atk":0,"def":252,"spa":0,"spd":4,"spe":0},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Water"}'::JSONB),
  (38, 'gen9ou', 'Sun Setter', '{"ability":"Drought","moves":["Weather Ball","Encore","Healing Wish","Will-O-Wisp"],"item":"Heat Rock","nature":"Timid","evs":{"hp":252,"atk":0,"def":4,"spa":0,"spd":0,"spe":252},"ivs":{"hp":31,"atk":0,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Ghost"}'::JSONB),
  (45, 'gen9pu', 'Physically Defensive', '{"ability":"Effect Spore","moves":["Strength Sap","Sludge Bomb","Giga Drain","Leech Seed"],"item":"Rocky Helmet","nature":"Bold","evs":{"hp":252,"atk":0,"def":252,"spa":0,"spd":4,"spe":0},"ivs":{"hp":31,"atk":0,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Water"}'::JSONB),
  (49, 'gen9pu', 'Quiver Dance', '{"ability":"Tinted Lens","moves":["Quiver Dance","Bug Buzz","Sludge Bomb","Morning Sun"],"item":"Heavy-Duty Boots","nature":"Timid","evs":{"hp":0,"atk":0,"def":0,"spa":252,"spd":4,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Fairy"}'::JSONB),
  (57, 'gen9zu', 'Offensive Stealth Rock', '{"ability":"Defiant","moves":["Stealth Rock","Close Combat","Rage Fist","U-turn"],"item":"Eviolite","nature":"Jolly","evs":{"hp":0,"atk":252,"def":0,"spa":0,"spd":4,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Ghost"}'::JSONB),
  (59, 'gen9pu', 'Curse', '{"ability":"Intimidate","moves":["Curse","Extreme Speed","Flare Blitz","Morning Sun"],"item":"Leftovers","nature":"Adamant","evs":{"hp":160,"atk":252,"def":0,"spa":0,"spd":0,"spe":96},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Normal"}'::JSONB),
  (62, 'gen9pu', 'Bulk Up', '{"ability":"Water Absorb","moves":["Bulk Up","Drain Punch","Knock Off","Substitute"],"item":"Leftovers","nature":"Careful","evs":{"hp":248,"atk":0,"def":0,"spa":0,"spd":164,"spe":96},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Dark"}'::JSONB),
  (71, 'gen9zu', 'All-Out Attacker', '{"ability":"Chlorophyll","moves":["Strength Sap","Power Whip","Poison Jab","Knock Off"],"item":"Heavy-Duty Boots","nature":"Adamant","evs":{"hp":0,"atk":252,"def":4,"spa":0,"spd":0,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Water"}'::JSONB),
  (73, 'gen9nu', 'Defensive Pivot', '{"ability":"Liquid Ooze","moves":["Flip Turn","Rapid Spin","Knock Off","Haze"],"item":"Leftovers","nature":"Jolly","evs":{"hp":252,"atk":0,"def":120,"spa":0,"spd":0,"spe":136},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Dark"}'::JSONB),
  (80, 'gen9ru', 'Calm Mind', '{"ability":"Regenerator","moves":["Calm Mind","Scald","Psychic Noise","Slack Off"],"item":"Heavy-Duty Boots","nature":"Bold","evs":{"hp":252,"atk":0,"def":252,"spa":0,"spd":4,"spe":0},"ivs":{"hp":31,"atk":0,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Poison"}'::JSONB),
  (82, 'gen9zu', 'Offensive Pivot', '{"ability":"Analytic","moves":["Thunderbolt","Flash Cannon","Volt Switch","Tri Attack"],"item":"Eviolite","nature":"Modest","evs":{"hp":172,"atk":0,"def":0,"spa":252,"spd":0,"spe":84},"ivs":{"hp":31,"atk":0,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Steel"}'::JSONB),
  (85, 'gen9zu', 'Swords Dance', '{"ability":"Tangled Feet","moves":["Swords Dance","Brave Bird","Low Kick","Quick Attack"],"item":"Heavy-Duty Boots","nature":"Jolly","evs":{"hp":0,"atk":252,"def":0,"spa":0,"spd":4,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Fighting"}'::JSONB),
  (89, 'gen9zu', 'Defensive', '{"ability":"Sticky Hold","moves":["Poison Jab","Knock Off","Zen Headbutt","Toxic"],"item":"Leftovers","nature":"Careful","evs":{"hp":252,"atk":0,"def":4,"spa":0,"spd":252,"spe":0},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Dark"}'::JSONB),
  (91, 'gen9ru', 'Shell Smash Sweeper', '{"ability":"Skill Link","moves":["Shell Smash","Icicle Spear","Drill Run","Tera Blast"],"item":"White Herb","nature":"Adamant","evs":{"hp":0,"atk":252,"def":0,"spa":4,"spd":0,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Electric"}'::JSONB),
  (93, 'gen9zu', 'Choiced', '{"ability":"Levitate","moves":["Shadow Ball","Sludge Bomb","Psychic","Trick"],"item":"Choice Scarf","nature":"Timid","evs":{"hp":0,"atk":0,"def":0,"spa":252,"spd":4,"spe":252},"ivs":{"hp":31,"atk":0,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Ghost"}'::JSONB),
  (94, 'gen9ru', 'Nasty Plot', '{"ability":"Cursed Body","moves":["Nasty Plot","Shadow Ball","Sludge Wave","Focus Blast"],"item":"Air Balloon","nature":"Timid","evs":{"hp":0,"atk":0,"def":4,"spa":252,"spd":0,"spe":252},"ivs":{"hp":31,"atk":0,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Ghost"}'::JSONB),
  (103, 'gen9pu', 'Choice Specs', '{"ability":"Chlorophyll","moves":["Leaf Storm","Psyshock","Ancient Power","Giga Drain"],"item":"Choice Specs","nature":"Modest","evs":{"hp":0,"atk":0,"def":4,"spa":252,"spd":0,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Steel"}'::JSONB),
  (106, 'gen9pu', 'Terrain Sweeper', '{"ability":"Unburden","moves":["Swords Dance","Close Combat","Knock Off","Stone Edge"],"item":"Psychic Seed","nature":"Adamant","evs":{"hp":0,"atk":252,"def":0,"spa":0,"spd":4,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Dark"}'::JSONB),
  (107, 'gen9zu', 'Bulky Rapid Spin', '{"ability":"Iron Fist","moves":["Drain Punch","Knock Off","Mach Punch","Rapid Spin"],"item":"Heavy-Duty Boots","nature":"Adamant","evs":{"hp":248,"atk":16,"def":0,"spa":0,"spd":244,"spe":0},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Dark"}'::JSONB),
  (110, 'gen9zu', 'Physical Wall', '{"ability":"Levitate","moves":["Sludge Bomb","Will-O-Wisp","Pain Split","Haze"],"item":"Rocky Helmet","nature":"Bold","evs":{"hp":252,"atk":0,"def":252,"spa":0,"spd":0,"spe":4},"ivs":{"hp":31,"atk":0,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Steel"}'::JSONB),
  (112, 'gen9pu', 'Stealth Rock', '{"ability":"Lightning Rod","moves":["Stealth Rock","Earthquake","Stone Edge","Swords Dance"],"item":"Eviolite","nature":"Adamant","evs":{"hp":248,"atk":16,"def":0,"spa":0,"spd":244,"spe":0},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Flying"}'::JSONB),
  (113, 'gen9nu', 'Defensive', '{"ability":"Natural Cure","moves":["Seismic Toss","Soft-Boiled","Heal Bell","Stealth Rock"],"item":"Eviolite","nature":"Bold","evs":{"hp":8,"atk":0,"def":252,"spa":0,"spd":248,"spe":0},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Dark"}'::JSONB),
  (123, 'gen9nu', 'Swords Dance', '{"ability":"Technician","moves":["Swords Dance","Dual Wingbeat","Close Combat","Trailblaze"],"item":"Eviolite","nature":"Jolly","evs":{"hp":0,"atk":252,"def":0,"spa":0,"spd":4,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Electric"}'::JSONB),
  (128, 'gen9zu', 'All-Out Attacker', '{"ability":"Sheer Force","moves":["Body Slam","Close Combat","Throat Chop","Substitute"],"item":"Life Orb","nature":"Jolly","evs":{"hp":0,"atk":252,"def":0,"spa":0,"spd":4,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Dark"}'::JSONB),
  (130, 'gen9uu', 'Dragon Dance', '{"ability":"Moxie","moves":["Dragon Dance","Waterfall","Scale Shot","Substitute"],"item":"Leftovers","nature":"Adamant","evs":{"hp":0,"atk":252,"def":0,"spa":0,"spd":4,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Dragon"}'::JSONB),
  (131, 'gen9zu', 'Special Tank', '{"ability":"Water Absorb","moves":["Freeze-Dry","Hydro Pump","Alluring Voice","Ice Beam"],"item":"Heavy-Duty Boots","nature":"Modest","evs":{"hp":0,"atk":0,"def":196,"spa":252,"spd":0,"spe":60},"ivs":{"hp":31,"atk":0,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Fairy"}'::JSONB),
  (132, 'gen9zu', 'Revenge Killer', '{"ability":"Imposter","moves":["Transform"],"item":"Choice Scarf","nature":"Relaxed","evs":{"hp":248,"atk":0,"def":252,"spa":0,"spd":8,"spe":0},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":0},"teraType":"Steel"}'::JSONB),
  (134, 'gen9nu', 'Wish Passer', '{"ability":"Water Absorb","moves":["Scald","Wish","Protect","Flip Turn"],"item":"Leftovers","nature":"Bold","evs":{"hp":252,"atk":0,"def":252,"spa":0,"spd":4,"spe":0},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Poison"}'::JSONB),
  (135, 'gen9zu', 'Calm Mind', '{"ability":"Quick Feet","moves":["Calm Mind","Thunderbolt","Volt Switch","Alluring Voice"],"item":"Heavy-Duty Boots","nature":"Timid","evs":{"hp":0,"atk":0,"def":0,"spa":252,"spd":4,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Fairy"}'::JSONB),
  (143, 'gen9pu', 'Curse', '{"ability":"Thick Fat","moves":["Curse","Body Slam","Heat Crash","Rest"],"item":"Leftovers","nature":"Careful","evs":{"hp":12,"atk":0,"def":244,"spa":0,"spd":252,"spe":0},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Fairy"}'::JSONB),
  (144, 'gen9zu', 'Special Wall', '{"ability":"Pressure","moves":["Roost","Freeze-Dry","U-turn","Haze"],"item":"Heavy-Duty Boots","nature":"Calm","evs":{"hp":248,"atk":0,"def":8,"spa":0,"spd":252,"spe":0},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Dragon"}'::JSONB),
  (145, 'gen9ou', 'Defensive', '{"ability":"Static","moves":["Hurricane","Volt Switch","Thunder Wave","Roost"],"item":"Heavy-Duty Boots","nature":"Bold","evs":{"hp":248,"atk":0,"def":252,"spa":8,"spd":0,"spe":0},"ivs":{"hp":31,"atk":0,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Steel"}'::JSONB),
  (146, 'gen9ou', 'Defensive', '{"ability":"Flame Body","moves":["Flamethrower","Roost","U-turn","Roar"],"item":"Heavy-Duty Boots","nature":"Bold","evs":{"hp":248,"atk":0,"def":248,"spa":0,"spd":0,"spe":12},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Fairy"}'::JSONB),
  (149, 'gen9ou', 'Dragon Dance', '{"ability":"Multiscale","moves":["Dragon Dance","Extreme Speed","Earthquake","Ice Spinner"],"item":"Heavy-Duty Boots","nature":"Adamant","evs":{"hp":0,"atk":252,"def":4,"spa":0,"spd":0,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Normal"}'::JSONB),
  (151, 'gen9uu', 'Suicide Lead', '{"ability":"Synchronize","moves":["Stealth Rock","Spikes","Taunt","Misty Explosion"],"item":"Red Card","nature":"Timid","evs":{"hp":252,"atk":0,"def":96,"spa":0,"spd":0,"spe":160},"ivs":{"hp":31,"atk":0,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Ghost"}'::JSONB),
  (157, 'gen9zu', 'Choice Specs', '{"ability":"Flash Fire","moves":["Eruption","Fire Blast","Focus Blast","Scorching Sands"],"item":"Choice Specs","nature":"Timid","evs":{"hp":0,"atk":0,"def":4,"spa":252,"spd":0,"spe":252},"ivs":{"hp":31,"atk":0,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Fire"}'::JSONB),
  (160, 'gen9ru', 'Setup Sweeper', '{"ability":"Sheer Force","moves":["Swords Dance","Aqua Jet","Ice Punch","Crunch"],"item":"Life Orb","nature":"Jolly","evs":{"hp":0,"atk":252,"def":0,"spa":0,"spd":4,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Dark"}'::JSONB),
  (171, 'gen9pu', 'RestTalk', '{"ability":"Water Absorb","moves":["Scald","Volt Switch","Rest","Sleep Talk"],"item":"Heavy-Duty Boots","nature":"Calm","evs":{"hp":216,"atk":0,"def":0,"spa":0,"spd":252,"spe":40},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Fairy"}'::JSONB),
  (184, 'gen9uu', 'Belly Drum', '{"ability":"Huge Power","moves":["Belly Drum","Play Rough","Liquidation","Aqua Jet"],"item":"Sitrus Berry","nature":"Adamant","evs":{"hp":4,"atk":252,"def":0,"spa":0,"spd":0,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Steel"}'::JSONB),
  (186, 'gen9ru', 'Perish Trapper', '{"ability":"Drizzle","moves":["Whirlpool","Perish Song","Ice Beam","Encore"],"item":"Damp Rock","nature":"Timid","evs":{"hp":252,"atk":0,"def":80,"spa":0,"spd":0,"spe":176},"ivs":{"hp":31,"atk":0,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Ghost"}'::JSONB),
  (195, 'gen9ru', 'Spikes', '{"ability":"Unaware","moves":["Spikes","Earthquake","Toxic","Recover"],"item":"Heavy-Duty Boots","nature":"Impish","evs":{"hp":252,"atk":4,"def":252,"spa":0,"spd":0,"spe":0},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Poison"}'::JSONB),
  (196, 'gen9nu', 'Magic Bounce Support', '{"ability":"Magic Bounce","moves":["Psychic Noise","Thunder Wave","Grass Knot","Morning Sun"],"item":"Rocky Helmet","nature":"Timid","evs":{"hp":252,"atk":0,"def":80,"spa":0,"spd":0,"spe":176},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Fairy"}'::JSONB),
  (197, 'gen9ru', 'Wish Support', '{"ability":"Inner Focus","moves":["Foul Play","Wish","Toxic","Protect"],"item":"Leftovers","nature":"Calm","evs":{"hp":252,"atk":0,"def":4,"spa":0,"spd":252,"spe":0},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Poison"}'::JSONB),
  (199, 'gen9uu', 'Utility Pivot', '{"ability":"Regenerator","moves":["Scald","Thunder Wave","Slack Off","Chilly Reception"],"item":"Heavy-Duty Boots","nature":"Sassy","evs":{"hp":252,"atk":0,"def":240,"spa":0,"spd":16,"spe":0},"ivs":{"hp":31,"atk":0,"def":31,"spa":31,"spd":31,"spe":0},"teraType":"Fairy"}'::JSONB),
  (205, 'gen9ru', 'Support', '{"ability":"Sturdy","moves":["Spikes","Body Press","Volt Switch","Gyro Ball"],"item":"Rocky Helmet","nature":"Relaxed","evs":{"hp":252,"atk":0,"def":164,"spa":0,"spd":92,"spe":0},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Ghost"}'::JSONB),
  (207, 'gen9nu', 'Physical Wall', '{"ability":"Immunity","moves":["Spikes","Earthquake","Knock Off","U-turn"],"item":"Eviolite","nature":"Impish","evs":{"hp":252,"atk":0,"def":200,"spa":0,"spd":0,"spe":56},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Water"}'::JSONB),
  (211, 'gen9pu', 'Physical Defensive', '{"ability":"Intimidate","moves":["Spikes","Barb Barrage","Flip Turn","Pain Split"],"item":"Rocky Helmet","nature":"Impish","evs":{"hp":252,"atk":0,"def":240,"spa":0,"spd":0,"spe":16},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Ground"}'::JSONB),
  (212, 'gen9uu', 'Pivot', '{"ability":"Technician","moves":["Swords Dance","Bullet Punch","U-turn","Knock Off"],"item":"Heavy-Duty Boots","nature":"Adamant","evs":{"hp":120,"atk":252,"def":0,"spa":0,"spd":0,"spe":136},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Steel"}'::JSONB),
  (214, 'gen9pu', 'Flame Orb', '{"ability":"Guts","moves":["Close Combat","Facade","Knock Off","Trailblaze"],"item":"Flame Orb","nature":"Jolly","evs":{"hp":0,"atk":252,"def":0,"spa":0,"spd":4,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Normal"}'::JSONB),
  (215, 'gen9zu', 'Fast Attacker', '{"ability":"Inner Focus","moves":["Knock Off","Triple Axel","Ice Shard","Swords Dance"],"item":"Heavy-Duty Boots","nature":"Jolly","evs":{"hp":0,"atk":252,"def":0,"spa":0,"spd":4,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Ice"}'::JSONB),
  (217, 'gen9zu', 'Wallbreaker', '{"ability":"Guts","moves":["Facade","Trailblaze","Close Combat","Play Rough"],"item":"Flame Orb","nature":"Jolly","evs":{"hp":0,"atk":252,"def":0,"spa":0,"spd":4,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Normal"}'::JSONB),
  (227, 'gen9uu', 'Physically Defensive', '{"ability":"Sturdy","moves":["Spikes","Body Press","Brave Bird","Roost"],"item":"Rocky Helmet","nature":"Impish","evs":{"hp":248,"atk":0,"def":252,"spa":0,"spd":8,"spe":0},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Ghost"}'::JSONB),
  (229, 'gen9zu', 'Wallbreaker', '{"ability":"Flash Fire","moves":["Nasty Plot","Fire Blast","Dark Pulse","Substitute"],"item":"Heavy-Duty Boots","nature":"Timid","evs":{"hp":0,"atk":0,"def":0,"spa":252,"spd":4,"spe":252},"ivs":{"hp":31,"atk":0,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Ghost"}'::JSONB),
  (230, 'gen9pu', 'CritDra', '{"ability":"Sniper","moves":["Focus Energy","Agility","Draco Meteor","Hydro Pump"],"item":"Scope Lens","nature":"Timid","evs":{"hp":0,"atk":0,"def":0,"spa":252,"spd":4,"spe":252},"ivs":{"hp":31,"atk":0,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Dragon"}'::JSONB),
  (232, 'gen9uu', 'Defensive', '{"ability":"Sturdy","moves":["Stealth Rock","Earthquake","Knock Off","Rapid Spin"],"item":"Leftovers","nature":"Impish","evs":{"hp":248,"atk":16,"def":244,"spa":0,"spd":0,"spe":0},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Ghost"}'::JSONB),
  (233, 'gen9pu', 'Offensive Trick Room', '{"ability":"Download","moves":["Trick Room","Tri Attack","Shadow Ball","Recover"],"item":"Eviolite","nature":"Quiet","evs":{"hp":252,"atk":0,"def":4,"spa":252,"spd":0,"spe":0},"ivs":{"hp":31,"atk":0,"def":31,"spa":31,"spd":31,"spe":0},"teraType":"Ghost"}'::JSONB),
  (235, 'gen9nu', 'Lead', '{"ability":"Technician","moves":["Ceaseless Edge","Stone Axe","Mortal Spin","Burning Bulwark"],"item":"Focus Sash","nature":"Jolly","evs":{"hp":0,"atk":252,"def":0,"spa":0,"spd":4,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Ghost"}'::JSONB),
  (237, 'gen9zu', 'Rapid Spin', '{"ability":"Technician","moves":["Rapid Spin","Close Combat","Triple Axel","Bullet Punch"],"item":"Protective Pads","nature":"Adamant","evs":{"hp":80,"atk":252,"def":0,"spa":0,"spd":0,"spe":176},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Steel"}'::JSONB),
  (242, 'gen9ru', 'Defensive', '{"ability":"Natural Cure","moves":["Seismic Toss","Thunder Wave","Stealth Rock","Soft-Boiled"],"item":"Heavy-Duty Boots","nature":"Bold","evs":{"hp":252,"atk":0,"def":252,"spa":0,"spd":4,"spe":0},"ivs":{"hp":31,"atk":0,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Dark"}'::JSONB),
  (243, 'gen9nu', 'Calm Mind', '{"ability":"Pressure","moves":["Calm Mind","Volt Switch","Scald","Shadow Ball"],"item":"Heavy-Duty Boots","nature":"Timid","evs":{"hp":0,"atk":0,"def":4,"spa":252,"spd":0,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Ghost"}'::JSONB),
  (244, 'gen9ru', 'All-Out Attacker', '{"ability":"Inner Focus","moves":["Extreme Speed","Sacred Fire","Stone Edge","Trailblaze"],"item":"Heavy-Duty Boots","nature":"Jolly","evs":{"hp":0,"atk":252,"def":4,"spa":0,"spd":0,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Normal"}'::JSONB),
  (245, 'gen9ru', 'Substitute + Calm Mind', '{"ability":"Pressure","moves":["Substitute","Calm Mind","Scald","Protect"],"item":"Leftovers","nature":"Timid","evs":{"hp":252,"atk":0,"def":4,"spa":0,"spd":0,"spe":252},"ivs":{"hp":31,"atk":0,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Dark"}'::JSONB),
  (248, 'gen9ou', 'Choice Band', '{"ability":"Sand Stream","moves":["Knock Off","Stone Edge","Low Kick","Ice Punch"],"item":"Choice Band","nature":"Adamant","evs":{"hp":0,"atk":252,"def":0,"spa":0,"spd":4,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Flying"}'::JSONB),
  (254, 'gen9zu', 'Choice Specs', '{"ability":"Unburden","moves":["Leaf Storm","Giga Drain","Focus Blast","Dragon Pulse"],"item":"Choice Specs","nature":"Timid","evs":{"hp":0,"atk":0,"def":0,"spa":252,"spd":4,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Dragon"}'::JSONB),
  (257, 'gen9ou', 'Swords Dance', '{"ability":"Speed Boost","moves":["Swords Dance","Close Combat","Flare Blitz","Stone Edge"],"item":"Life Orb","nature":"Adamant","evs":{"hp":0,"atk":252,"def":4,"spa":0,"spd":0,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Fighting"}'::JSONB),
  (260, 'gen9nu', 'Utility Tank', '{"ability":"Torrent","moves":["Stealth Rock","Earthquake","Flip Turn","Knock Off"],"item":"Leftovers","nature":"Careful","evs":{"hp":252,"atk":4,"def":0,"spa":0,"spd":252,"spe":0},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Fairy"}'::JSONB),
  (272, 'gen9nu', 'Rain Dance Sweeper', '{"ability":"Swift Swim","moves":["Hydro Pump","Giga Drain","Ice Beam","Rain Dance"],"item":"Life Orb","nature":"Modest","evs":{"hp":0,"atk":0,"def":0,"spa":252,"spd":4,"spe":252},"ivs":{"hp":31,"atk":0,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Water"}'::JSONB),
  (275, 'gen9ru', 'Chlorophyll Sweeper', '{"ability":"Chlorophyll","moves":["Growth","Solar Blade","Knock Off","Heat Wave"],"item":"Life Orb","nature":"Hasty","evs":{"hp":0,"atk":252,"def":0,"spa":4,"spd":0,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Dark"}'::JSONB),
  (279, 'gen9ou', 'Rain Setter', '{"ability":"Drizzle","moves":["Hurricane","U-turn","Roost","Knock Off"],"item":"Damp Rock","nature":"Relaxed","evs":{"hp":248,"atk":0,"def":252,"spa":0,"spd":8,"spe":0},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":0},"teraType":"Ground"}'::JSONB),
  (282, 'gen9ru', 'Choice Scarf', '{"ability":"Trace","moves":["Moonblast","Psychic","Trick","Healing Wish"],"item":"Choice Scarf","nature":"Timid","evs":{"hp":0,"atk":0,"def":4,"spa":252,"spd":0,"spe":252},"ivs":{"hp":31,"atk":0,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Fairy"}'::JSONB),
  (286, 'gen9ru', 'Poison Heal', '{"ability":"Poison Heal","moves":["Close Combat","Seed Bomb","Facade","Protect"],"item":"Toxic Orb","nature":"Adamant","evs":{"hp":252,"atk":80,"def":0,"spa":0,"spd":0,"spe":176},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Steel"}'::JSONB),
  (297, 'gen9pu', 'Bulk Up', '{"ability":"Guts","moves":["Bulk Up","Drain Punch","Knock Off","Bullet Punch"],"item":"Leftovers","nature":"Adamant","evs":{"hp":12,"atk":200,"def":0,"spa":0,"spd":252,"spe":44},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Steel"}'::JSONB),
  (302, 'gen9zu', 'Physical Wall', '{"ability":"Prankster","moves":["Encore","Will-O-Wisp","Recover","Knock Off"],"item":"Heavy-Duty Boots","nature":"Impish","evs":{"hp":252,"atk":0,"def":252,"spa":0,"spd":4,"spe":0},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Poison"}'::JSONB),
  (308, 'gen9zu', 'Choice Scarf', '{"ability":"Pure Power","moves":["Close Combat","Zen Headbutt","Ice Punch","Trick"],"item":"Choice Scarf","nature":"Jolly","evs":{"hp":0,"atk":252,"def":0,"spa":0,"spd":4,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Fighting"}'::JSONB),
  (317, 'gen9zu', 'Physically Defensive', '{"ability":"Sticky Hold","moves":["Sludge Bomb","Ice Beam","Thunder Wave","Encore"],"item":"Leftovers","nature":"Bold","evs":{"hp":252,"atk":0,"def":252,"spa":0,"spd":4,"spe":0},"ivs":{"hp":31,"atk":0,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Dark"}'::JSONB),
  (323, 'gen9zu', 'Specially Defensive', '{"ability":"Solid Rock","moves":["Stealth Rock","Lava Plume","Earth Power","Roar"],"item":"Leftovers","nature":"Calm","evs":{"hp":252,"atk":0,"def":4,"spa":0,"spd":252,"spe":0},"ivs":{"hp":31,"atk":0,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Water"}'::JSONB),
  (324, 'gen9ou', 'Sun Setter', '{"ability":"Drought","moves":["Lava Plume","Rapid Spin","Stealth Rock","Will-O-Wisp"],"item":"Heat Rock","nature":"Bold","evs":{"hp":248,"atk":0,"def":252,"spa":0,"spd":8,"spe":0},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Flying"}'::JSONB),
  (330, 'gen9nu', 'Choice Scarf', '{"ability":"Levitate","moves":["Earthquake","Outrage","U-turn","Stone Edge"],"item":"Choice Scarf","nature":"Jolly","evs":{"hp":0,"atk":252,"def":0,"spa":0,"spd":4,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Steel"}'::JSONB),
  (334, 'gen9nu', 'Utility', '{"ability":"Natural Cure","moves":["Defog","Roost","Brave Bird","Will-O-Wisp"],"item":"Heavy-Duty Boots","nature":"Impish","evs":{"hp":252,"atk":0,"def":240,"spa":0,"spd":0,"spe":16},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Steel"}'::JSONB),
  (335, 'gen9zu', 'Wallbreaker', '{"ability":"Toxic Boost","moves":["Swords Dance","Facade","Knock Off","Quick Attack"],"item":"Toxic Orb","nature":"Jolly","evs":{"hp":0,"atk":252,"def":0,"spa":0,"spd":4,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Normal"}'::JSONB),
  (340, 'gen9zu', 'Entry Hazard Setter', '{"ability":"Oblivious","moves":["Stealth Rock","Earth Power","Surf","Spikes"],"item":"Heavy-Duty Boots","nature":"Sassy","evs":{"hp":248,"atk":0,"def":8,"spa":0,"spd":252,"spe":0},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Ghost"}'::JSONB),
  (342, 'gen9ru', 'Swords Dance', '{"ability":"Adaptability","moves":["Swords Dance","Crabhammer","Knock Off","Aqua Jet"],"item":"Life Orb","nature":"Adamant","evs":{"hp":0,"atk":252,"def":0,"spa":0,"spd":4,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Water"}'::JSONB),
  (350, 'gen9pu', 'Physically Defensive', '{"ability":"Marvel Scale","moves":["Recover","Scald","Flip Turn","Alluring Voice"],"item":"Heavy-Duty Boots","nature":"Bold","evs":{"hp":252,"atk":0,"def":248,"spa":0,"spd":0,"spe":8},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Fairy"}'::JSONB),
  (373, 'gen9uu', 'Offensive', '{"ability":"Intimidate","moves":["Draco Meteor","Hurricane","Earthquake","Roost"],"item":"Heavy-Duty Boots","nature":"Timid","evs":{"hp":0,"atk":0,"def":4,"spa":252,"spd":0,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Fairy"}'::JSONB),
  (376, 'gen9uu', 'Choice Band', '{"ability":"Clear Body","moves":["Heavy Slam","Earthquake","Knock Off","Bullet Punch"],"item":"Choice Band","nature":"Adamant","evs":{"hp":0,"atk":252,"def":0,"spa":0,"spd":4,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Steel"}'::JSONB),
  (377, 'gen9zu', 'Physical Wall', '{"ability":"Sturdy","moves":["Stealth Rock","Rock Blast","Body Press","Iron Defense"],"item":"Leftovers","nature":"Impish","evs":{"hp":252,"atk":0,"def":16,"spa":0,"spd":240,"spe":0},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Poison"}'::JSONB),
  (379, 'gen9ru', 'Stealth Rock', '{"ability":"Clear Body","moves":["Stealth Rock","Heavy Slam","Body Press","Iron Defense"],"item":"Leftovers","nature":"Impish","evs":{"hp":252,"atk":0,"def":180,"spa":0,"spd":76,"spe":0},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Ghost"}'::JSONB),
  (380, 'gen9ou', 'Calm Mind', '{"ability":"Levitate","moves":["Calm Mind","Stored Power","Aura Sphere","Recover"],"item":"Weakness Policy","nature":"Timid","evs":{"hp":252,"atk":0,"def":4,"spa":0,"spd":0,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Poison"}'::JSONB),
  (381, 'gen9uu', 'Choice Specs', '{"ability":"Levitate","moves":["Draco Meteor","Luster Purge","Surf","Trick"],"item":"Choice Specs","nature":"Timid","evs":{"hp":0,"atk":0,"def":0,"spa":252,"spd":4,"spe":252},"ivs":{"hp":31,"atk":0,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Dragon"}'::JSONB),
  (385, 'gen9ru', 'Utility', '{"ability":"Serene Grace","moves":["Stealth Rock","Iron Head","Body Slam","Encore"],"item":"Leftovers","nature":"Jolly","evs":{"hp":252,"atk":0,"def":0,"spa":0,"spd":4,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Water"}'::JSONB),
  (389, 'gen9ru', 'Shell Smash', '{"ability":"Overgrow","moves":["Shell Smash","Headlong Rush","Bullet Seed","Rock Blast"],"item":"Loaded Dice","nature":"Jolly","evs":{"hp":0,"atk":252,"def":0,"spa":0,"spd":4,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Fairy"}'::JSONB),
  (392, 'gen9nu', 'Choice Specs', '{"ability":"Blaze","moves":["Flamethrower","Overheat","Focus Blast","Vacuum Wave"],"item":"Choice Specs","nature":"Timid","evs":{"hp":0,"atk":0,"def":4,"spa":252,"spd":0,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Fire"}'::JSONB),
  (395, 'gen9ru', 'Offensive', '{"ability":"Competitive","moves":["Surf","Ice Beam","Grass Knot","Roost"],"item":"Leftovers","nature":"Modest","evs":{"hp":72,"atk":0,"def":72,"spa":148,"spd":0,"spe":216},"ivs":{"hp":31,"atk":0,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Fairy"}'::JSONB),
  (398, 'gen9nu', 'Choice Attacker', '{"ability":"Reckless","moves":["Brave Bird","Quick Attack","Close Combat","U-turn"],"item":"Choice Band","nature":"Jolly","evs":{"hp":0,"atk":252,"def":4,"spa":0,"spd":0,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Flying"}'::JSONB),
  (411, 'gen9nu', 'Special Wall', '{"ability":"Soundproof","moves":["Stealth Rock","Body Press","Heavy Slam","Foul Play"],"item":"Leftovers","nature":"Careful","evs":{"hp":252,"atk":0,"def":4,"spa":0,"spd":252,"spe":0},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Fairy"}'::JSONB),
  (419, 'gen9pu', 'Choice Band', '{"ability":"Water Veil","moves":["Wave Crash","Flip Turn","Aqua Jet","Ice Spinner"],"item":"Choice Band","nature":"Jolly","evs":{"hp":0,"atk":252,"def":4,"spa":0,"spd":0,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Water"}'::JSONB),
  (423, 'gen9ru', 'Defensive', '{"ability":"Sticky Hold","moves":["Spikes","Earthquake","Ice Beam","Recover"],"item":"Rocky Helmet","nature":"Relaxed","evs":{"hp":252,"atk":0,"def":252,"spa":0,"spd":4,"spe":0},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Ghost"}'::JSONB),
  (424, 'gen9pu', 'Offensive Pivot', '{"ability":"Technician","moves":["Fake Out","U-turn","Knock Off","Triple Axel"],"item":"Heavy-Duty Boots","nature":"Jolly","evs":{"hp":0,"atk":252,"def":0,"spa":0,"spd":4,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Ice"}'::JSONB),
  (426, 'gen9zu', 'Defog', '{"ability":"Unburden","moves":["Defog","Strength Sap","Will-O-Wisp","Hex"],"item":"Heavy-Duty Boots","nature":"Timid","evs":{"hp":0,"atk":0,"def":252,"spa":0,"spd":4,"spe":252},"ivs":{"hp":31,"atk":0,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Fairy"}'::JSONB),
  (429, 'gen9pu', 'Nasty Plot', '{"ability":"Levitate","moves":["Nasty Plot","Shadow Ball","Draining Kiss","Substitute"],"item":"Leftovers","nature":"Timid","evs":{"hp":0,"atk":0,"def":4,"spa":252,"spd":0,"spe":252},"ivs":{"hp":31,"atk":0,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Fairy"}'::JSONB),
  (430, 'gen9zu', 'All-Out Attacker', '{"ability":"Moxie","moves":["Sucker Punch","Brave Bird","U-turn","Night Slash"],"item":"Heavy-Duty Boots","nature":"Jolly","evs":{"hp":0,"atk":252,"def":0,"spa":0,"spd":4,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Dark"}'::JSONB),
  (435, 'gen9zu', 'Offensive Utility', '{"ability":"Aftermath","moves":["Knock Off","Gunk Shot","Sucker Punch","Taunt"],"item":"Heavy-Duty Boots","nature":"Jolly","evs":{"hp":0,"atk":252,"def":0,"spa":0,"spd":4,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Dark"}'::JSONB),
  (437, 'gen9nu', 'Utility', '{"ability":"Levitate","moves":["Stealth Rock","Psychic Noise","Body Press","Heavy Slam"],"item":"Leftovers","nature":"Calm","evs":{"hp":252,"atk":0,"def":4,"spa":0,"spd":252,"spe":0},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Fairy"}'::JSONB),
  (442, 'gen9zu', 'Offensive Trick Room', '{"ability":"Infiltrator","moves":["Trick Room","Nasty Plot","Dark Pulse","Psyshock"],"item":"Leftovers","nature":"Quiet","evs":{"hp":252,"atk":0,"def":0,"spa":252,"spd":4,"spe":0},"ivs":{"hp":31,"atk":0,"def":31,"spa":31,"spd":31,"spe":0},"teraType":"Dark"}'::JSONB),
  (445, 'gen9ou', 'TankChomp', '{"ability":"Rough Skin","moves":["Earthquake","Dragon Tail","Stealth Rock","Spikes"],"item":"Rocky Helmet","nature":"Impish","evs":{"hp":252,"atk":0,"def":216,"spa":0,"spd":0,"spe":40},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Ghost"}'::JSONB),
  (448, 'gen9ru', 'Swords Dance', '{"ability":"Inner Focus","moves":["Swords Dance","Close Combat","Meteor Mash","Extreme Speed"],"item":"Life Orb","nature":"Jolly","evs":{"hp":0,"atk":252,"def":0,"spa":0,"spd":4,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Normal"}'::JSONB),
  (450, 'gen9uu', 'Tank', '{"ability":"Sand Stream","moves":["Stealth Rock","Ice Fang","Earthquake","Slack Off"],"item":"Leftovers","nature":"Impish","evs":{"hp":248,"atk":0,"def":112,"spa":0,"spd":148,"spe":0},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Water"}'::JSONB),
  (454, 'gen9zu', 'Wallbreaker', '{"ability":"Dry Skin","moves":["Close Combat","Gunk Shot","Swords Dance","Knock Off"],"item":"Life Orb","nature":"Jolly","evs":{"hp":0,"atk":252,"def":0,"spa":0,"spd":4,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Dark"}'::JSONB),
  (460, 'gen9zu', 'Aurora Veil', '{"ability":"Snow Warning","moves":["Aurora Veil","Blizzard","Giga Drain","Earth Power"],"item":"Heavy-Duty Boots","nature":"Modest","evs":{"hp":248,"atk":0,"def":0,"spa":252,"spd":8,"spe":0},"ivs":{"hp":31,"atk":0,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Water"}'::JSONB),
  (461, 'gen9uu', 'Swords Dance', '{"ability":"Pickpocket","moves":["Swords Dance","Triple Axel","Knock Off","Low Kick"],"item":"Heavy-Duty Boots","nature":"Jolly","evs":{"hp":0,"atk":252,"def":0,"spa":0,"spd":4,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Ghost"}'::JSONB),
  (462, 'gen9ru', 'Choice Specs', '{"ability":"Analytic","moves":["Thunderbolt","Flash Cannon","Volt Switch","Tri Attack"],"item":"Choice Specs","nature":"Modest","evs":{"hp":0,"atk":0,"def":0,"spa":252,"spd":4,"spe":252},"ivs":{"hp":31,"atk":0,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Grass"}'::JSONB),
  (464, 'gen9nu', 'Stealth Rock', '{"ability":"Solid Rock","moves":["Stealth Rock","Earthquake","Stone Edge","Temper Flare"],"item":"Leftovers","nature":"Adamant","evs":{"hp":252,"atk":16,"def":0,"spa":0,"spd":240,"spe":0},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Dragon"}'::JSONB),
  (467, 'gen9zu', 'All-out Attacker', '{"ability":"Flame Body","moves":["Fire Blast","Scorching Sands","Thunderbolt","Knock Off"],"item":"Heavy-Duty Boots","nature":"Timid","evs":{"hp":0,"atk":0,"def":4,"spa":252,"spd":0,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Ground"}'::JSONB),
  (469, 'gen9ru', 'Speed Boost Sweeper', '{"ability":"Speed Boost","moves":["Bug Buzz","Air Slash","Shadow Ball","Protect"],"item":"Throat Spray","nature":"Modest","evs":{"hp":0,"atk":0,"def":4,"spa":252,"spd":0,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Ghost"}'::JSONB),
  (472, 'gen9ou', 'Swords Dance', '{"ability":"Poison Heal","moves":["Swords Dance","Facade","Knock Off","Protect"],"item":"Toxic Orb","nature":"Careful","evs":{"hp":244,"atk":0,"def":36,"spa":0,"spd":228,"spe":0},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Normal"}'::JSONB),
  (473, 'gen9uu', 'Substitute', '{"ability":"Thick Fat","moves":["Substitute","Earthquake","Icicle Crash","Trailblaze"],"item":"Leftovers","nature":"Adamant","evs":{"hp":0,"atk":252,"def":0,"spa":0,"spd":4,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Grass"}'::JSONB),
  (474, 'gen9ru', 'Agility', '{"ability":"Download","moves":["Agility","Tera Blast","Ice Beam","Thunderbolt"],"item":"Heavy-Duty Boots","nature":"Modest","evs":{"hp":0,"atk":0,"def":0,"spa":252,"spd":4,"spe":252},"ivs":{"hp":31,"atk":0,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Ground"}'::JSONB),
  (475, 'gen9ru', 'Setup Sweeper', '{"ability":"Sharpness","moves":["Swords Dance","Sacred Sword","Psycho Cut","Leaf Blade"],"item":"Lum Berry","nature":"Jolly","evs":{"hp":0,"atk":252,"def":0,"spa":0,"spd":4,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Steel"}'::JSONB),
  (476, 'gen9zu', 'Sand Attacker', '{"ability":"Sand Force","moves":["Meteor Beam","Earth Power","Flash Cannon","Dazzling Gleam"],"item":"Power Herb","nature":"Modest","evs":{"hp":168,"atk":0,"def":0,"spa":252,"spd":0,"spe":88},"ivs":{"hp":31,"atk":0,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Fairy"}'::JSONB),
  (477, 'gen9zu', 'Bulky Attacker', '{"ability":"Pressure","moves":["Poltergeist","Leech Life","Shadow Sneak","Pain Split"],"item":"Weakness Policy","nature":"Adamant","evs":{"hp":252,"atk":252,"def":0,"spa":0,"spd":4,"spe":0},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Bug"}'::JSONB),
  (478, 'gen9zu', 'Lead', '{"ability":"Cursed Body","moves":["Spikes","Taunt","Destiny Bond","Icy Wind"],"item":"Focus Sash","nature":"Timid","evs":{"hp":0,"atk":0,"def":0,"spa":252,"spd":4,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Ghost"}'::JSONB),
  (479, 'gen9zu', 'Choice Scarf', '{"ability":"Levitate","moves":["Thunderbolt","Shadow Ball","Volt Switch","Trick"],"item":"Choice Scarf","nature":"Timid","evs":{"hp":0,"atk":0,"def":0,"spa":252,"spd":4,"spe":252},"ivs":{"hp":31,"atk":0,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Electric"}'::JSONB),
  (480, 'gen9nu', 'Nasty Plot', '{"ability":"Levitate","moves":["Nasty Plot","Psychic Noise","Draining Kiss","Encore"],"item":"Leftovers","nature":"Timid","evs":{"hp":0,"atk":0,"def":4,"spa":252,"spd":0,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Fairy"}'::JSONB),
  (481, 'gen9zu', 'Physically Defensive Pivot', '{"ability":"Levitate","moves":["Stealth Rock","Psychic Noise","U-turn","Knock Off"],"item":"Rocky Helmet","nature":"Bold","evs":{"hp":252,"atk":0,"def":252,"spa":0,"spd":4,"spe":0},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Steel"}'::JSONB),
  (482, 'gen9ru', 'Lead', '{"ability":"Levitate","moves":["Stealth Rock","Taunt","Explosion","Flamethrower"],"item":"Focus Sash","nature":"Naive","evs":{"hp":0,"atk":252,"def":4,"spa":0,"spd":0,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Ghost"}'::JSONB),
  (485, 'gen9ou', 'Offensive', '{"ability":"Flash Fire","moves":["Magma Storm","Earth Power","Taunt","Stealth Rock"],"item":"Leftovers","nature":"Timid","evs":{"hp":0,"atk":0,"def":0,"spa":252,"spd":4,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Grass"}'::JSONB),
  (488, 'gen9ru', 'Lunar Dance', '{"ability":"Levitate","moves":["Lunar Dance","Ice Beam","Trick","Thunder Wave"],"item":"Choice Scarf","nature":"Timid","evs":{"hp":252,"atk":0,"def":0,"spa":4,"spd":0,"spe":252},"ivs":{"hp":31,"atk":0,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Fairy"}'::JSONB),
  (490, 'gen9ou', 'Tail Glow', '{"ability":"Hydration","moves":["Tail Glow","Surf","Alluring Voice","Substitute"],"item":"Leftovers","nature":"Timid","evs":{"hp":0,"atk":0,"def":4,"spa":252,"spd":0,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Fairy"}'::JSONB),
  (491, 'gen9ou', 'Nasty Plot', '{"ability":"Bad Dreams","moves":["Nasty Plot","Dark Pulse","Sludge Bomb","Ice Beam"],"item":"Leftovers","nature":"Timid","evs":{"hp":0,"atk":0,"def":0,"spa":252,"spd":4,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Poison"}'::JSONB),
  (492, 'gen9pu', 'Offensive', '{"ability":"Natural Cure","moves":["Seed Flare","Earth Power","Air Slash","Synthesis"],"item":"Life Orb","nature":"Timid","evs":{"hp":0,"atk":0,"def":0,"spa":252,"spd":4,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Ground"}'::JSONB),
  (497, 'gen9uu', 'Offensive', '{"ability":"Contrary","moves":["Leaf Storm","Dragon Pulse","Synthesis","Glare"],"item":"Leftovers","nature":"Timid","evs":{"hp":0,"atk":0,"def":4,"spa":252,"spd":0,"spe":252},"ivs":{"hp":31,"atk":0,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Steel"}'::JSONB),
  (500, 'gen9pu', 'Wallbreaker', '{"ability":"Reckless","moves":["Flare Blitz","Close Combat","Sucker Punch","Knock Off"],"item":"Heavy-Duty Boots","nature":"Adamant","evs":{"hp":0,"atk":252,"def":4,"spa":0,"spd":0,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Dark"}'::JSONB),
  (503, 'gen9zu', 'Offensive Pivot', '{"ability":"Torrent","moves":["Hydro Pump","Ice Beam","Flip Turn","Knock Off"],"item":"Heavy-Duty Boots","nature":"Timid","evs":{"hp":0,"atk":4,"def":0,"spa":252,"spd":0,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Grass"}'::JSONB),
  (530, 'gen9uu', 'Utility', '{"ability":"Mold Breaker","moves":["Stealth Rock","Earthquake","Iron Head","Rapid Spin"],"item":"Leftovers","nature":"Adamant","evs":{"hp":24,"atk":56,"def":0,"spa":0,"spd":252,"spe":176},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Ghost"}'::JSONB),
  (533, 'gen9zu', 'Bulky Attacker', '{"ability":"Sheer Force","moves":["Drain Punch","Knock Off","Mach Punch","Defog"],"item":"Eviolite","nature":"Adamant","evs":{"hp":252,"atk":252,"def":0,"spa":0,"spd":4,"spe":0},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Steel"}'::JSONB),
  (534, 'gen9uu', 'Flame Orb Guts', '{"ability":"Guts","moves":["Drain Punch","Facade","Knock Off","Mach Punch"],"item":"Flame Orb","nature":"Adamant","evs":{"hp":0,"atk":252,"def":4,"spa":0,"spd":0,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Normal"}'::JSONB),
  (547, 'gen9zu', 'Choice Specs', '{"ability":"Infiltrator","moves":["Moonblast","Energy Ball","U-turn","Switcheroo"],"item":"Choice Specs","nature":"Timid","evs":{"hp":0,"atk":0,"def":0,"spa":252,"spd":4,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Fairy"}'::JSONB),
  (549, 'gen9zu', 'Quiver Dance', '{"ability":"Chlorophyll","moves":["Quiver Dance","Giga Drain","Alluring Voice","Encore"],"item":"Life Orb","nature":"Modest","evs":{"hp":0,"atk":0,"def":0,"spa":252,"spd":4,"spe":252},"ivs":{"hp":31,"atk":0,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Poison"}'::JSONB),
  (553, 'gen9ru', 'Choice Band', '{"ability":"Intimidate","moves":["Earthquake","Knock Off","Gunk Shot","Close Combat"],"item":"Choice Band","nature":"Jolly","evs":{"hp":0,"atk":252,"def":0,"spa":0,"spd":4,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Dark"}'::JSONB),
  (560, 'gen9nu', 'Bulk Up', '{"ability":"Intimidate","moves":["Bulk Up","Drain Punch","Knock Off","Rest"],"item":"Leftovers","nature":"Careful","evs":{"hp":252,"atk":0,"def":0,"spa":0,"spd":192,"spe":64},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Poison"}'::JSONB),
  (571, 'gen9pu', 'Choice Specs', '{"ability":"Illusion","moves":["Dark Pulse","Sludge Bomb","Flamethrower","Grass Knot"],"item":"Choice Specs","nature":"Timid","evs":{"hp":0,"atk":0,"def":4,"spa":252,"spd":0,"spe":252},"ivs":{"hp":31,"atk":0,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Dark"}'::JSONB),
  (573, 'gen9nu', 'Tidy Up', '{"ability":"Technician","moves":["Tidy Up","Tail Slap","Knock Off","Encore"],"item":"Loaded Dice","nature":"Jolly","evs":{"hp":0,"atk":252,"def":0,"spa":0,"spd":4,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Ghost"}'::JSONB),
  (579, 'gen9ru', 'Calm Mind', '{"ability":"Magic Guard","moves":["Calm Mind","Psychic Noise","Focus Blast","Recover"],"item":"Leftovers","nature":"Bold","evs":{"hp":252,"atk":0,"def":252,"spa":0,"spd":4,"spe":0},"ivs":{"hp":31,"atk":0,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Water"}'::JSONB),
  (581, 'gen9zu', 'Defog', '{"ability":"Big Pecks","moves":["Defog","Roost","Brave Bird","Flip Turn"],"item":"Heavy-Duty Boots","nature":"Impish","evs":{"hp":252,"atk":0,"def":224,"spa":0,"spd":0,"spe":32},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Ground"}'::JSONB),
  (591, 'gen9pu', 'Physically Defensive Pivot', '{"ability":"Regenerator","moves":["Giga Drain","Toxic","Foul Play","Synthesis"],"item":"Heavy-Duty Boots","nature":"Bold","evs":{"hp":252,"atk":0,"def":252,"spa":0,"spd":4,"spe":0},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Water"}'::JSONB),
  (594, 'gen9ou', 'WishFish (Wish Passer)', '{"ability":"Regenerator","moves":["Flip Turn","Wish","Protect","Scald"],"item":"Heavy-Duty Boots","nature":"Relaxed","evs":{"hp":252,"atk":0,"def":252,"spa":0,"spd":4,"spe":0},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":0},"teraType":"Ghost"}'::JSONB),
  (596, 'gen9pu', 'All-Out-Attacker', '{"ability":"Compound Eyes","moves":["Thunder","Bug Buzz","Volt Switch","Energy Ball"],"item":"Heavy-Duty Boots","nature":"Timid","evs":{"hp":0,"atk":0,"def":0,"spa":252,"spd":4,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Electric"}'::JSONB),
  (604, 'gen9zu', 'Defensive Pivot', '{"ability":"Levitate","moves":["Knock Off","U-turn","Discharge","Dragon Tail"],"item":"Assault Vest","nature":"Sassy","evs":{"hp":252,"atk":0,"def":4,"spa":0,"spd":252,"spe":0},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":0},"teraType":"Steel"}'::JSONB),
  (609, 'gen9nu', 'Choice Specs', '{"ability":"Flash Fire","moves":["Fire Blast","Shadow Ball","Energy Ball","Trick"],"item":"Choice Specs","nature":"Timid","evs":{"hp":0,"atk":0,"def":0,"spa":252,"spd":4,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Grass"}'::JSONB),
  (612, 'gen9uu', 'Choice Band', '{"ability":"Mold Breaker","moves":["First Impression","Outrage","Earthquake","Poison Jab"],"item":"Choice Band","nature":"Jolly","evs":{"hp":0,"atk":252,"def":0,"spa":0,"spd":4,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Dragon"}'::JSONB),
  (614, 'gen9zu', 'Snow Sweeper', '{"ability":"Slush Rush","moves":["Swords Dance","Icicle Spear","Close Combat","Earthquake"],"item":"Loaded Dice","nature":"Adamant","evs":{"hp":0,"atk":252,"def":4,"spa":0,"spd":0,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Fighting"}'::JSONB),
  (615, 'gen9zu', 'Hazard Remover', '{"ability":"Levitate","moves":["Rapid Spin","Freeze-Dry","Recover","Haze"],"item":"Heavy-Duty Boots","nature":"Timid","evs":{"hp":252,"atk":0,"def":0,"spa":4,"spd":0,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Steel"}'::JSONB),
  (623, 'gen9pu', 'Choice Band', '{"ability":"No Guard","moves":["Poltergeist","Earthquake","Dynamic Punch","Ice Punch"],"item":"Choice Band","nature":"Adamant","evs":{"hp":0,"atk":252,"def":0,"spa":0,"spd":4,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Dark"}'::JSONB),
  (625, 'gen9ru', 'Swords Dance', '{"ability":"Defiant","moves":["Swords Dance","Sucker Punch","Iron Head","Throat Chop"],"item":"Eviolite","nature":"Adamant","evs":{"hp":80,"atk":252,"def":0,"spa":0,"spd":0,"spe":176},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Flying"}'::JSONB),
  (628, 'gen9nu', 'Bulk Up', '{"ability":"Defiant","moves":["Bulk Up","Facade","Shadow Claw","Roost"],"item":"Heavy-Duty Boots","nature":"Careful","evs":{"hp":248,"atk":0,"def":0,"spa":0,"spd":164,"spe":96},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Ground"}'::JSONB),
  (630, 'gen9uu', 'Physically Defensive', '{"ability":"Overcoat","moves":["Foul Play","Toxic","Roost","U-turn"],"item":"Heavy-Duty Boots","nature":"Impish","evs":{"hp":252,"atk":0,"def":240,"spa":0,"spd":0,"spe":16},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Steel"}'::JSONB),
  (635, 'gen9uu', 'Nasty Plot', '{"ability":"Levitate","moves":["Nasty Plot","Draco Meteor","Flamethrower","Thunder Wave"],"item":"Leftovers","nature":"Timid","evs":{"hp":0,"atk":0,"def":0,"spa":252,"spd":4,"spe":252},"ivs":{"hp":31,"atk":0,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Poison"}'::JSONB),
  (638, 'gen9uu', 'Setter', '{"ability":"Justified","moves":["Stealth Rock","Body Press","Thunder Wave","Volt Switch"],"item":"Rocky Helmet","nature":"Timid","evs":{"hp":112,"atk":0,"def":144,"spa":0,"spd":0,"spe":252},"ivs":{"hp":31,"atk":0,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Water"}'::JSONB),
  (639, 'gen9ru', 'Stealth Rock', '{"ability":"Justified","moves":["Stealth Rock","Close Combat","Rock Blast","Swords Dance"],"item":"Focus Sash","nature":"Jolly","evs":{"hp":0,"atk":252,"def":0,"spa":0,"spd":4,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Ghost"}'::JSONB),
  (640, 'gen9zu', 'Swords Dance', '{"ability":"Justified","moves":["Swords Dance","Close Combat","Leaf Blade","Stone Edge"],"item":"Heavy-Duty Boots","nature":"Jolly","evs":{"hp":0,"atk":252,"def":0,"spa":0,"spd":4,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Rock"}'::JSONB),
  (641, 'gen9nu', 'Offensive Pivot', '{"ability":"Defiant","moves":["Bleakwind Storm","Knock Off","U-turn","Heat Wave"],"item":"Heavy-Duty Boots","nature":"Timid","evs":{"hp":0,"atk":0,"def":4,"spa":252,"spd":0,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Steel"}'::JSONB),
  (642, 'gen9uu', 'Pivot', '{"ability":"Prankster","moves":["Volt Switch","Grass Knot","Knock Off","Taunt"],"item":"Heavy-Duty Boots","nature":"Timid","evs":{"hp":0,"atk":0,"def":0,"spa":252,"spd":4,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Electric"}'::JSONB),
  (646, 'gen9ou', 'Choice Specs', '{"ability":"Pressure","moves":["Ice Beam","Freeze-Dry","Earth Power","Draco Meteor"],"item":"Choice Specs","nature":"Timid","evs":{"hp":0,"atk":0,"def":0,"spa":252,"spd":4,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Ice"}'::JSONB),
  (647, 'gen9uu', 'Pivot', '{"ability":"Justified","moves":["Surf","Focus Blast","Vacuum Wave","Flip Turn"],"item":"Heavy-Duty Boots","nature":"Timid","evs":{"hp":0,"atk":0,"def":0,"spa":252,"spd":4,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Fighting"}'::JSONB),
  (648, 'gen9nu', 'Choice Item', '{"ability":"Serene Grace","moves":["Psychic","Hyper Voice","Shadow Ball","Trick"],"item":"Choice Specs","nature":"Timid","evs":{"hp":0,"atk":0,"def":0,"spa":252,"spd":4,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Fighting"}'::JSONB),
  (652, 'gen9ru', 'Spikes', '{"ability":"Bulletproof","moves":["Spikes","Body Press","Knock Off","Synthesis"],"item":"Rocky Helmet","nature":"Impish","evs":{"hp":252,"atk":0,"def":204,"spa":0,"spd":0,"spe":52},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Ghost"}'::JSONB),
  (655, 'gen9pu', 'Nasty Plot', '{"ability":"Blaze","moves":["Nasty Plot","Fire Blast","Psyshock","Encore"],"item":"Heavy-Duty Boots","nature":"Timid","evs":{"hp":0,"atk":0,"def":4,"spa":252,"spd":0,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Fairy"}'::JSONB),
  (658, 'gen9uu', 'Choice Specs', '{"ability":"Protean","moves":["Surf","Dark Pulse","Ice Beam","Water Shuriken"],"item":"Choice Specs","nature":"Timid","evs":{"hp":0,"atk":0,"def":0,"spa":252,"spd":4,"spe":252},"ivs":{"hp":31,"atk":0,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Water"}'::JSONB),
  (663, 'gen9uu', 'Fast Pivot', '{"ability":"Flame Body","moves":["Flare Blitz","U-turn","Roost","Defog"],"item":"Heavy-Duty Boots","nature":"Jolly","evs":{"hp":248,"atk":0,"def":8,"spa":0,"spd":0,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Grass"}'::JSONB),
  (668, 'gen9zu', 'Special Attacker', '{"ability":"Unnerve","moves":["Fire Blast","Hyper Voice","Taunt","Will-O-Wisp"],"item":"Heavy-Duty Boots","nature":"Timid","evs":{"hp":0,"atk":0,"def":4,"spa":252,"spd":0,"spe":252},"ivs":{"hp":31,"atk":0,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Ghost"}'::JSONB),
  (671, 'gen9pu', 'Choice Scarf', '{"ability":"Flower Veil","moves":["Moonblast","Synthesis","Trick","Calm Mind"],"item":"Choice Scarf","nature":"Timid","evs":{"hp":0,"atk":0,"def":4,"spa":252,"spd":0,"spe":252},"ivs":{"hp":31,"atk":0,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Fairy"}'::JSONB),
  (687, 'gen9zu', 'RestTalk', '{"ability":"Contrary","moves":["Superpower","Knock Off","Rest","Sleep Talk"],"item":"Leftovers","nature":"Careful","evs":{"hp":252,"atk":0,"def":0,"spa":0,"spd":252,"spe":4},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Poison"}'::JSONB),
  (693, 'gen9zu', 'Wallbreaker', '{"ability":"Mega Launcher","moves":["Water Pulse","Dragon Pulse","Aura Sphere","Dark Pulse"],"item":"Choice Specs","nature":"Modest","evs":{"hp":0,"atk":0,"def":4,"spa":252,"spd":0,"spe":252},"ivs":{"hp":31,"atk":0,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Dragon"}'::JSONB),
  (700, 'gen9nu', 'Choice Specs', '{"ability":"Pixilate","moves":["Hyper Voice","Psychic","Shadow Ball","Draining Kiss"],"item":"Choice Specs","nature":"Modest","evs":{"hp":0,"atk":0,"def":4,"spa":252,"spd":0,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Fairy"}'::JSONB),
  (701, 'gen9uu', 'Sweeper', '{"ability":"Unburden","moves":["Swords Dance","Close Combat","Acrobatics","Taunt"],"item":"Psychic Seed","nature":"Adamant","evs":{"hp":132,"atk":252,"def":0,"spa":0,"spd":0,"spe":124},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Fire"}'::JSONB),
  (706, 'gen9nu', 'Heavy-Duty Boots', '{"ability":"Sap Sipper","moves":["Draco Meteor","Fire Blast","Sludge Bomb","Knock Off"],"item":"Heavy-Duty Boots","nature":"Modest","evs":{"hp":76,"atk":0,"def":0,"spa":252,"spd":0,"spe":180},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Poison"}'::JSONB),
  (707, 'gen9nu', 'Spikes Support', '{"ability":"Prankster","moves":["Spikes","Thunder Wave","Foul Play","Dazzling Gleam"],"item":"Leftovers","nature":"Calm","evs":{"hp":252,"atk":0,"def":4,"spa":0,"spd":252,"spe":0},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Water"}'::JSONB),
  (709, 'gen9zu', 'All-Out Attacker', '{"ability":"Natural Cure","moves":["Poltergeist","Wood Hammer","Sucker Punch","Rest"],"item":"Life Orb","nature":"Adamant","evs":{"hp":0,"atk":252,"def":0,"spa":0,"spd":4,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Dark"}'::JSONB),
  (713, 'gen9nu', 'Physical Wall', '{"ability":"Sturdy","moves":["Recover","Rapid Spin","Body Press","Avalanche"],"item":"Heavy-Duty Boots","nature":"Impish","evs":{"hp":252,"atk":4,"def":252,"spa":0,"spd":0,"spe":0},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Poison"}'::JSONB),
  (715, 'gen9ru', 'Offensive Pivot', '{"ability":"Frisk","moves":["Draco Meteor","Flamethrower","U-turn","Roost"],"item":"Heavy-Duty Boots","nature":"Timid","evs":{"hp":0,"atk":0,"def":0,"spa":252,"spd":4,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Steel"}'::JSONB),
  (719, 'gen9ru', 'Trick Room Sweeper', '{"ability":"Clear Body","moves":["Trick Room","Meteor Beam","Moonblast","Earth Power"],"item":"Power Herb","nature":"Quiet","evs":{"hp":248,"atk":0,"def":0,"spa":252,"spd":8,"spe":0},"ivs":{"hp":31,"atk":0,"def":31,"spa":31,"spd":31,"spe":0},"teraType":"Water"}'::JSONB),
  (720, 'gen9pu', 'Choice Scarf', '{"ability":"Magician","moves":["Psyshock","Shadow Ball","Focus Blast","Trick"],"item":"Choice Scarf","nature":"Timid","evs":{"hp":0,"atk":0,"def":0,"spa":252,"spd":4,"spe":252},"ivs":{"hp":31,"atk":0,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Fighting"}'::JSONB),
  (721, 'gen9uu', 'Offensive / Trapper', '{"ability":"Water Absorb","moves":["Steam Eruption","Flamethrower","Sludge Bomb","Taunt"],"item":"Heavy-Duty Boots","nature":"Modest","evs":{"hp":60,"atk":0,"def":0,"spa":252,"spd":0,"spe":196},"ivs":{"hp":31,"atk":0,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Ground"}'::JSONB),
  (724, 'gen9nu', 'Swords Dance', '{"ability":"Long Reach","moves":["Swords Dance","Spirit Shackle","Leaf Blade","Shadow Sneak"],"item":"Spell Tag","nature":"Adamant","evs":{"hp":0,"atk":252,"def":0,"spa":0,"spd":4,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Ghost"}'::JSONB),
  (727, 'gen9nu', 'Swords Dance', '{"ability":"Intimidate","moves":["Swords Dance","Flare Blitz","Knock Off","U-turn"],"item":"Heavy-Duty Boots","nature":"Adamant","evs":{"hp":0,"atk":252,"def":0,"spa":0,"spd":4,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Poison"}'::JSONB),
  (730, 'gen9ou', 'Assault Vest', '{"ability":"Torrent","moves":["Moonblast","Psychic Noise","Surf","Flip Turn"],"item":"Assault Vest","nature":"Modest","evs":{"hp":252,"atk":0,"def":0,"spa":208,"spd":48,"spe":0},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Poison"}'::JSONB),
  (738, 'gen9zu', 'Sticky Web Lead', '{"ability":"Levitate","moves":["Sticky Web","Volt Switch","Bug Buzz","Energy Ball"],"item":"Focus Sash","nature":"Modest","evs":{"hp":0,"atk":0,"def":4,"spa":252,"spd":0,"spe":252},"ivs":{"hp":31,"atk":0,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Ghost"}'::JSONB),
  (740, 'gen9zu', 'Choice Band', '{"ability":"Iron Fist","moves":["Ice Hammer","Close Combat","Earthquake","Knock Off"],"item":"Choice Band","nature":"Adamant","evs":{"hp":252,"atk":252,"def":0,"spa":0,"spd":4,"spe":0},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Ice"}'::JSONB),
  (741, 'gen9pu', 'Offensive Quiver Dance', '{"ability":"Dancer","moves":["Quiver Dance","Revelation Dance","Hurricane","Roost"],"item":"Heavy-Duty Boots","nature":"Timid","evs":{"hp":0,"atk":0,"def":0,"spa":252,"spd":4,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Ground"}'::JSONB),
  (743, 'gen9ru', 'Sticky Web', '{"ability":"Shield Dust","moves":["Sticky Web","Moonblast","Stun Spore","Psychic Noise"],"item":"Focus Sash","nature":"Timid","evs":{"hp":0,"atk":0,"def":0,"spa":252,"spd":4,"spe":252},"ivs":{"hp":31,"atk":0,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Ghost"}'::JSONB),
  (745, 'gen9zu', 'Swords Dance', '{"ability":"Sand Rush","moves":["Swords Dance","Stone Edge","Close Combat","Accelerock"],"item":"Life Orb","nature":"Jolly","evs":{"hp":0,"atk":252,"def":0,"spa":0,"spd":4,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Fighting"}'::JSONB),
  (748, 'gen9uu', 'Mixed Defense', '{"ability":"Regenerator","moves":["Surf","Toxic","Haze","Recover"],"item":"Heavy-Duty Boots","nature":"Bold","evs":{"hp":248,"atk":0,"def":152,"spa":0,"spd":108,"spe":0},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Fairy"}'::JSONB),
  (750, 'gen9pu', 'Physical Wall', '{"ability":"Stamina","moves":["Stealth Rock","Earthquake","Body Press","Roar"],"item":"Leftovers","nature":"Impish","evs":{"hp":252,"atk":0,"def":252,"spa":0,"spd":4,"spe":0},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Water"}'::JSONB),
  (752, 'gen9nu', 'Sticky Web', '{"ability":"Water Bubble","moves":["Liquidation","Lunge","Sticky Web","Endeavor"],"item":"Focus Sash","nature":"Adamant","evs":{"hp":68,"atk":252,"def":0,"spa":0,"spd":0,"spe":188},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Ghost"}'::JSONB),
  (754, 'gen9zu', 'Defog', '{"ability":"Contrary","moves":["Defog","Synthesis","Leaf Storm","Superpower"],"item":"Heavy-Duty Boots","nature":"Sassy","evs":{"hp":248,"atk":0,"def":8,"spa":0,"spd":252,"spe":0},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Poison"}'::JSONB),
  (758, 'gen9pu', 'Nasty Plot', '{"ability":"Corrosion","moves":["Nasty Plot","Fire Blast","Sludge Bomb","Encore"],"item":"Heavy-Duty Boots","nature":"Timid","evs":{"hp":0,"atk":0,"def":0,"spa":252,"spd":4,"spe":252},"ivs":{"hp":31,"atk":0,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Dark"}'::JSONB),
  (763, 'gen9nu', 'Offensive', '{"ability":"Queenly Majesty","moves":["Power Whip","Knock Off","Rapid Spin","Triple Axel"],"item":"Heavy-Duty Boots","nature":"Jolly","evs":{"hp":0,"atk":252,"def":0,"spa":0,"spd":4,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Dragon"}'::JSONB),
  (764, 'gen9ru', 'Setup Sweeper', '{"ability":"Triage","moves":["Growth","Draining Kiss","Stored Power","Taunt"],"item":"Life Orb","nature":"Timid","evs":{"hp":236,"atk":0,"def":0,"spa":252,"spd":0,"spe":20},"ivs":{"hp":31,"atk":0,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Fairy"}'::JSONB),
  (766, 'gen9pu', 'Choice Scarf', '{"ability":"Defiant","moves":["Close Combat","Knock Off","U-turn","Earthquake"],"item":"Choice Scarf","nature":"Jolly","evs":{"hp":0,"atk":252,"def":4,"spa":0,"spd":0,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Fighting"}'::JSONB),
  (770, 'gen9pu', 'Physically Defensive', '{"ability":"Water Compaction","moves":["Shore Up","Stealth Rock","Shadow Ball","Scorching Sands"],"item":"Colbur Berry","nature":"Bold","evs":{"hp":252,"atk":0,"def":252,"spa":0,"spd":4,"spe":0},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Water"}'::JSONB),
  (774, 'gen9zu', 'Shell Smash', '{"ability":"Shields Down","moves":["Shell Smash","Acrobatics","Earthquake","Stone Edge"],"item":"White Herb","nature":"Adamant","evs":{"hp":0,"atk":252,"def":0,"spa":0,"spd":4,"spe":252},"ivs":{"hp":30,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Grass"}'::JSONB),
  (778, 'gen9ru', 'Swords Dance', '{"ability":"Disguise","moves":["Swords Dance","Shadow Claw","Drain Punch","Shadow Sneak"],"item":"Life Orb","nature":"Jolly","evs":{"hp":0,"atk":252,"def":0,"spa":0,"spd":4,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Ghost"}'::JSONB),
  (779, 'gen9pu', 'Choice Scarf', '{"ability":"Strong Jaw","moves":["Psychic Fangs","Wave Crash","Flip Turn","Crunch"],"item":"Choice Scarf","nature":"Jolly","evs":{"hp":0,"atk":252,"def":4,"spa":0,"spd":0,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Psychic"}'::JSONB),
  (784, 'gen9ou', 'Physical Clangorous Soul', '{"ability":"Soundproof","moves":["Clangorous Soul","Drain Punch","Shadow Claw","Substitute"],"item":"Leftovers","nature":"Jolly","evs":{"hp":248,"atk":8,"def":0,"spa":0,"spd":0,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Ghost"}'::JSONB),
  (800, 'gen9ru', 'Dragon Dance', '{"ability":"Prism Armor","moves":["Dragon Dance","Photon Geyser","Earthquake","X-Scissor"],"item":"Lum Berry","nature":"Jolly","evs":{"hp":0,"atk":252,"def":4,"spa":0,"spd":0,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Fairy"}'::JSONB),
  (811, 'gen9uu', 'Terrain Setter', '{"ability":"Grassy Surge","moves":["Grassy Glide","Knock Off","Taunt","U-turn"],"item":"Terrain Extender","nature":"Careful","evs":{"hp":252,"atk":0,"def":0,"spa":0,"spd":240,"spe":16},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Steel"}'::JSONB),
  (812, 'gen9ou', 'Swords Dance', '{"ability":"Grassy Surge","moves":["Swords Dance","Grassy Glide","Knock Off","Wood Hammer"],"item":"Life Orb","nature":"Adamant","evs":{"hp":0,"atk":252,"def":4,"spa":0,"spd":0,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Grass"}'::JSONB),
  (815, 'gen9ou', 'Offensive Pivot', '{"ability":"Libero","moves":["Pyro Ball","U-turn","Court Change","Sucker Punch"],"item":"Heavy-Duty Boots","nature":"Jolly","evs":{"hp":0,"atk":252,"def":0,"spa":0,"spd":4,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Fire"}'::JSONB),
  (818, 'gen9nu', 'Choice Specs', '{"ability":"Torrent","moves":["Hydro Pump","Ice Beam","Dark Pulse","U-turn"],"item":"Choice Specs","nature":"Timid","evs":{"hp":0,"atk":0,"def":0,"spa":252,"spd":4,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Water"}'::JSONB),
  (823, 'gen9ou', 'Defensive', '{"ability":"Pressure","moves":["Brave Bird","Defog","U-turn","Roost"],"item":"Rocky Helmet","nature":"Impish","evs":{"hp":248,"atk":0,"def":252,"spa":0,"spd":8,"spe":0},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Dragon"}'::JSONB),
  (839, 'gen9pu', 'Defensive', '{"ability":"Flame Body","moves":["Rapid Spin","Stealth Rock","Flamethrower","Earth Power"],"item":"Heavy-Duty Boots","nature":"Calm","evs":{"hp":248,"atk":0,"def":8,"spa":0,"spd":252,"spe":0},"ivs":{"hp":31,"atk":0,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Ghost"}'::JSONB),
  (844, 'gen9zu', 'Physical Wall', '{"ability":"Shed Skin","moves":["Stealth Rock","Earthquake","Rock Blast","Rest"],"item":"Rocky Helmet","nature":"Impish","evs":{"hp":252,"atk":0,"def":252,"spa":0,"spd":4,"spe":0},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Poison"}'::JSONB),
  (845, 'gen9pu', 'Defog', '{"ability":"Gulp Missile","moves":["Defog","Roost","Surf","Brave Bird"],"item":"Heavy-Duty Boots","nature":"Bold","evs":{"hp":248,"atk":0,"def":188,"spa":0,"spd":56,"spe":16},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Steel"}'::JSONB),
  (847, 'gen9ru', 'Offensive Pivot', '{"ability":"Swift Swim","moves":["Liquidation","Flip Turn","Close Combat","Aqua Jet"],"item":"Choice Band","nature":"Jolly","evs":{"hp":0,"atk":252,"def":4,"spa":0,"spd":0,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Water"}'::JSONB),
  (849, 'gen9ru', 'Choice Specs', '{"ability":"Punk Rock","moves":["Boomburst","Overdrive","Sludge Wave","Volt Switch"],"item":"Choice Specs","nature":"Modest","evs":{"hp":0,"atk":0,"def":0,"spa":252,"spd":4,"spe":252},"ivs":{"hp":31,"atk":0,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Normal"}'::JSONB),
  (858, 'gen9ou', 'Pain Split', '{"ability":"Magic Bounce","moves":["Psychic Noise","Draining Kiss","Pain Split","Nuzzle"],"item":"Rocky Helmet","nature":"Bold","evs":{"hp":252,"atk":0,"def":204,"spa":0,"spd":0,"spe":52},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Water"}'::JSONB),
  (861, 'gen9pu', 'Bulky Pivot', '{"ability":"Prankster","moves":["Parting Shot","Thunder Wave","Spirit Break","Sucker Punch"],"item":"Heavy-Duty Boots","nature":"Careful","evs":{"hp":252,"atk":0,"def":4,"spa":0,"spd":252,"spe":0},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Steel"}'::JSONB),
  (863, 'gen9zu', 'All-Out Attacker', '{"ability":"Tough Claws","moves":["Iron Head","Close Combat","Knock Off","U-turn"],"item":"Assault Vest","nature":"Adamant","evs":{"hp":248,"atk":252,"def":0,"spa":0,"spd":8,"spe":0},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Fairy"}'::JSONB),
  (869, 'gen9pu', 'Double Dance', '{"ability":"Aroma Veil","moves":["Calm Mind","Acid Armor","Draining Kiss","Stored Power"],"item":"Leftovers","nature":"Bold","evs":{"hp":252,"atk":0,"def":192,"spa":0,"spd":0,"spe":64},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Poison"}'::JSONB),
  (871, 'gen9nu', 'Terrain Setter', '{"ability":"Electric Surge","moves":["Discharge","Scald","Spikes","Recover"],"item":"Terrain Extender","nature":"Bold","evs":{"hp":252,"atk":0,"def":252,"spa":0,"spd":4,"spe":0},"ivs":{"hp":31,"atk":0,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Water"}'::JSONB),
  (873, 'gen9pu', 'Defog', '{"ability":"Ice Scales","moves":["Defog","U-turn","Ice Beam","Stun Spore"],"item":"Heavy-Duty Boots","nature":"Modest","evs":{"hp":248,"atk":0,"def":0,"spa":20,"spd":240,"spe":0},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Water"}'::JSONB),
  (876, 'gen9nu', 'Terrain Setter', '{"ability":"Psychic Surge","moves":["Expanding Force","Dazzling Gleam","Encore","Healing Wish"],"item":"Terrain Extender","nature":"Timid","evs":{"hp":252,"atk":0,"def":4,"spa":0,"spd":0,"spe":252},"ivs":{"hp":31,"atk":0,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Fairy"}'::JSONB),
  (877, 'gen9zu', 'Offensive Utility', '{"ability":"Hunger Switch","moves":["Aura Wheel","Knock Off","Rapid Spin","Parting Shot"],"item":"Heavy-Duty Boots","nature":"Jolly","evs":{"hp":0,"atk":252,"def":0,"spa":0,"spd":4,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Dark"}'::JSONB),
  (879, 'gen9nu', 'Stealth Rock', '{"ability":"Sheer Force","moves":["Stealth Rock","Iron Head","Knock Off","Whirlwind"],"item":"Leftovers","nature":"Careful","evs":{"hp":252,"atk":0,"def":0,"spa":0,"spd":228,"spe":28},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Dragon"}'::JSONB),
  (884, 'gen9nu', 'Offensive Support', '{"ability":"Light Metal","moves":["Draco Meteor","Flash Cannon","Stealth Rock","Thunder Wave"],"item":"Eviolite","nature":"Modest","evs":{"hp":160,"atk":0,"def":0,"spa":96,"spd":252,"spe":0},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Fairy"}'::JSONB),
  (887, 'gen9ou', 'Boots Pivot', '{"ability":"Infiltrator","moves":["Dragon Darts","Hex","Will-O-Wisp","U-turn"],"item":"Heavy-Duty Boots","nature":"Naive","evs":{"hp":0,"atk":4,"def":0,"spa":252,"spd":0,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Ghost"}'::JSONB),
  (889, 'gen9ou', 'IronPress', '{"ability":"Dauntless Shield","moves":["Iron Defense","Body Press","Crunch","Roar"],"item":"Leftovers","nature":"Jolly","evs":{"hp":252,"atk":0,"def":88,"spa":0,"spd":0,"spe":168},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Fire"}'::JSONB),
  (893, 'gen9ou', 'Swords Dance', '{"ability":"Leaf Guard","moves":["Swords Dance","Knock Off","Power Whip","Synthesis"],"item":"Leftovers","nature":"Jolly","evs":{"hp":0,"atk":252,"def":4,"spa":0,"spd":0,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Poison"}'::JSONB),
  (895, 'gen9ru', 'Choice Scarf', '{"ability":"Dragon''s Maw","moves":["Dragon Energy","Draco Meteor","Earth Power","Dragon Pulse"],"item":"Choice Scarf","nature":"Timid","evs":{"hp":0,"atk":0,"def":0,"spa":252,"spd":4,"spe":252},"ivs":{"hp":31,"atk":0,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Dragon"}'::JSONB),
  (896, 'gen9pu', 'Swords Dance', '{"ability":"Chilling Neigh","moves":["Swords Dance","Icicle Crash","Close Combat","High Horsepower"],"item":"Heavy-Duty Boots","nature":"Adamant","evs":{"hp":128,"atk":252,"def":0,"spa":0,"spd":4,"spe":124},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Poison"}'::JSONB),
  (900, 'gen9ru', 'Lead', '{"ability":"Sharpness","moves":["Stone Axe","X-Scissor","Swords Dance","Close Combat"],"item":"Focus Sash","nature":"Jolly","evs":{"hp":0,"atk":252,"def":4,"spa":0,"spd":0,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Ghost"}'::JSONB),
  (901, 'gen9ou', 'Guts Wallbreaker', '{"ability":"Guts","moves":["Facade","Headlong Rush","Fire Punch","Swords Dance"],"item":"Flame Orb","nature":"Adamant","evs":{"hp":248,"atk":252,"def":8,"spa":0,"spd":0,"spe":0},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Normal"}'::JSONB),
  (902, 'gen9nu', 'Substitute', '{"ability":"Adaptability","moves":["Substitute","Liquidation","Phantom Force","Aqua Jet"],"item":"Leftovers","nature":"Adamant","evs":{"hp":0,"atk":252,"def":0,"spa":0,"spd":4,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Water"}'::JSONB),
  (904, 'gen9nu', 'Setup Sweeper', '{"ability":"Intimidate","moves":["Swords Dance","Gunk Shot","Throat Chop","Scale Shot"],"item":"Loaded Dice","nature":"Jolly","evs":{"hp":0,"atk":252,"def":4,"spa":0,"spd":0,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Dragon"}'::JSONB),
  (905, 'gen9ou', 'Choice Scarf', '{"ability":"Contrary","moves":["Moonblast","Earth Power","Mystical Fire","Healing Wish"],"item":"Choice Scarf","nature":"Modest","evs":{"hp":0,"atk":0,"def":0,"spa":252,"spd":4,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Ground"}'::JSONB),
  (908, 'gen9ou', 'Boots Pivot', '{"ability":"Protean","moves":["Knock Off","Flower Trick","Triple Axel","U-turn"],"item":"Heavy-Duty Boots","nature":"Jolly","evs":{"hp":0,"atk":252,"def":0,"spa":0,"spd":4,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Grass"}'::JSONB),
  (911, 'gen9uu', 'Defensive', '{"ability":"Unaware","moves":["Torch Song","Hex","Will-O-Wisp","Slack Off"],"item":"Heavy-Duty Boots","nature":"Bold","evs":{"hp":252,"atk":0,"def":16,"spa":0,"spd":240,"spe":0},"ivs":{"hp":31,"atk":0,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Fairy"}'::JSONB),
  (914, 'gen9ou', 'Assault Vest', '{"ability":"Moxie","moves":["Close Combat","Aqua Step","Knock Off","Rapid Spin"],"item":"Assault Vest","nature":"Adamant","evs":{"hp":0,"atk":252,"def":4,"spa":0,"spd":0,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Steel"}'::JSONB),
  (920, 'gen9uu', 'Swords Dance', '{"ability":"Tinted Lens","moves":["Swords Dance","Knock Off","Sucker Punch","Protect"],"item":"Black Glasses","nature":"Jolly","evs":{"hp":0,"atk":252,"def":0,"spa":0,"spd":4,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Dark"}'::JSONB),
  (923, 'gen9pu', 'Offensive', '{"ability":"Iron Fist","moves":["Double Shock","Close Combat","Ice Punch","Mach Punch"],"item":"Life Orb","nature":"Jolly","evs":{"hp":0,"atk":252,"def":4,"spa":0,"spd":0,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Electric"}'::JSONB),
  (925, 'gen9ru', 'Tidy Up', '{"ability":"Technician","moves":["Tidy Up","Population Bomb","Bite","Encore"],"item":"Wide Lens","nature":"Jolly","evs":{"hp":0,"atk":252,"def":4,"spa":0,"spd":0,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Ghost"}'::JSONB),
  (930, 'gen9zu', 'Choice Specs', '{"ability":"Seed Sower","moves":["Leaf Storm","Hyper Voice","Earth Power","Alluring Voice"],"item":"Choice Specs","nature":"Modest","evs":{"hp":72,"atk":0,"def":0,"spa":252,"spd":0,"spe":184},"ivs":{"hp":31,"atk":0,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Fairy"}'::JSONB),
  (934, 'gen9ou', 'Stealth Rock', '{"ability":"Sturdy","moves":["Stealth Rock","Salt Cure","Recover","Protect"],"item":"Leftovers","nature":"Careful","evs":{"hp":252,"atk":0,"def":52,"spa":0,"spd":204,"spe":0},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Fairy"}'::JSONB),
  (937, 'gen9ou', 'Swords Dance', '{"ability":"Weak Armor","moves":["Swords Dance","Bitter Blade","Shadow Sneak","Poltergeist"],"item":"Life Orb","nature":"Adamant","evs":{"hp":0,"atk":252,"def":0,"spa":0,"spd":4,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Ghost"}'::JSONB),
  (939, 'gen9nu', 'Defensive', '{"ability":"Static","moves":["Volt Switch","Slack Off","Toxic","Muddy Water"],"item":"Rocky Helmet","nature":"Bold","evs":{"hp":252,"atk":0,"def":252,"spa":0,"spd":4,"spe":0},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Fairy"}'::JSONB),
  (941, 'gen9nu', 'Offensive Pivot', '{"ability":"Volt Absorb","moves":["Air Slash","Thunderbolt","U-turn","Roost"],"item":"Heavy-Duty Boots","nature":"Timid","evs":{"hp":160,"atk":0,"def":0,"spa":96,"spd":0,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Steel"}'::JSONB),
  (943, 'gen9zu', 'Choiced', '{"ability":"Stakeout","moves":["Crunch","Play Rough","Psychic Fangs","Destiny Bond"],"item":"Choice Scarf","nature":"Jolly","evs":{"hp":0,"atk":252,"def":0,"spa":0,"spd":4,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Dark"}'::JSONB),
  (947, 'gen9nu', 'Offensive Utility', '{"ability":"Wind Rider","moves":["Poltergeist","Power Whip","Rapid Spin","Strength Sap"],"item":"Heavy-Duty Boots","nature":"Jolly","evs":{"hp":0,"atk":252,"def":0,"spa":0,"spd":4,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Fairy"}'::JSONB),
  (949, 'gen9zu', 'Offensive Rapid Spin', '{"ability":"Mycelium Might","moves":["Leaf Storm","Earth Power","Rapid Spin","Knock Off"],"item":"Heavy-Duty Boots","nature":"Timid","evs":{"hp":0,"atk":0,"def":4,"spa":252,"spd":0,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Water"}'::JSONB),
  (952, 'gen9uu', 'Sun Sweeper', '{"ability":"Chlorophyll","moves":["Flamethrower","Overheat","Giga Drain","Solar Beam"],"item":"Choice Specs","nature":"Modest","evs":{"hp":0,"atk":0,"def":0,"spa":252,"spd":4,"spe":252},"ivs":{"hp":31,"atk":0,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Fire"}'::JSONB),
  (959, 'gen9uu', 'Bulky Wall', '{"ability":"Pickpocket","moves":["Stealth Rock","Gigaton Hammer","Knock Off","Encore"],"item":"Leftovers","nature":"Careful","evs":{"hp":248,"atk":0,"def":184,"spa":0,"spd":76,"spe":0},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Ghost"}'::JSONB),
  (962, 'gen9pu', 'Offensive', '{"ability":"Big Pecks","moves":["Knock Off","Brave Bird","Sucker Punch","Taunt"],"item":"Heavy-Duty Boots","nature":"Adamant","evs":{"hp":0,"atk":252,"def":4,"spa":0,"spd":0,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Dark"}'::JSONB),
  (966, 'gen9uu', 'The Car: Shift Gear', '{"ability":"Filter","moves":["Shift Gear","Gunk Shot","High Horsepower","Temper Flare"],"item":"Air Balloon","nature":"Adamant","evs":{"hp":0,"atk":252,"def":4,"spa":0,"spd":0,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Fire"}'::JSONB),
  (967, 'gen9ru', 'Assault Vest', '{"ability":"Regenerator","moves":["Rapid Spin","Knock Off","U-turn","Draco Meteor"],"item":"Assault Vest","nature":"Timid","evs":{"hp":104,"atk":0,"def":0,"spa":0,"spd":152,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Fairy"}'::JSONB),
  (968, 'gen9zu', 'Defensive', '{"ability":"Earth Eater","moves":["Stealth Rock","Heavy Slam","Body Press","Iron Defense"],"item":"Leftovers","nature":"Impish","evs":{"hp":252,"atk":0,"def":16,"spa":0,"spd":240,"spe":0},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Ghost"}'::JSONB),
  (970, 'gen9ou', 'Lead', '{"ability":"Toxic Debris","moves":["Stealth Rock","Mortal Spin","Earth Power","Power Gem"],"item":"Red Card","nature":"Bold","evs":{"hp":252,"atk":0,"def":252,"spa":0,"spd":4,"spe":0},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Ghost"}'::JSONB),
  (972, 'gen9nu', 'Offensive Spinblocker', '{"ability":"Fluffy","moves":["Poltergeist","Play Rough","Shadow Sneak","Pain Split"],"item":"Heavy-Duty Boots","nature":"Adamant","evs":{"hp":0,"atk":252,"def":196,"spa":0,"spd":0,"spe":60},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Fairy"}'::JSONB),
  (973, 'gen9nu', 'Choice Item', '{"ability":"Scrappy","moves":["Close Combat","Brave Bird","U-turn","Roost"],"item":"Choice Scarf","nature":"Jolly","evs":{"hp":0,"atk":252,"def":0,"spa":0,"spd":4,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Fighting"}'::JSONB),
  (975, 'gen9ru', 'Belly Drum', '{"ability":"Slush Rush","moves":["Belly Drum","Ice Spinner","Earthquake","Ice Shard"],"item":"Sitrus Berry","nature":"Jolly","evs":{"hp":4,"atk":252,"def":0,"spa":0,"spd":0,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Ground"}'::JSONB),
  (976, 'gen9zu', 'Fillet Away Sweeper', '{"ability":"Sharpness","moves":["Fillet Away","Aqua Cutter","Psycho Cut","Aqua Jet"],"item":"Sitrus Berry","nature":"Adamant","evs":{"hp":4,"atk":252,"def":0,"spa":0,"spd":0,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Water"}'::JSONB),
  (977, 'gen9ou', 'Unaware Wall', '{"ability":"Unaware","moves":["Rest","Curse","Waterfall","Sleep Talk"],"item":"Heavy-Duty Boots","nature":"Impish","evs":{"hp":252,"atk":0,"def":252,"spa":0,"spd":4,"spe":0},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Fighting"}'::JSONB),
  (978, 'gen9pu', 'Nasty Plot', '{"ability":"Storm Drain","moves":["Nasty Plot","Draco Meteor","Surf","Rapid Spin"],"item":"Heavy-Duty Boots","nature":"Timid","evs":{"hp":0,"atk":0,"def":0,"spa":252,"spd":4,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Fairy"}'::JSONB),
  (980, 'gen9uu', 'Unaware', '{"ability":"Unaware","moves":["Earthquake","Recover","Toxic","Stealth Rock"],"item":"Heavy-Duty Boots","nature":"Careful","evs":{"hp":248,"atk":0,"def":84,"spa":0,"spd":176,"spe":0},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Dark"}'::JSONB),
  (981, 'gen9zu', 'Double Dance', '{"ability":"Armor Tail","moves":["Agility","Nasty Plot","Psyshock","Dazzling Gleam"],"item":"Leftovers","nature":"Timid","evs":{"hp":0,"atk":0,"def":0,"spa":252,"spd":4,"spe":252},"ivs":{"hp":31,"atk":0,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Fairy"}'::JSONB),
  (982, 'gen9nu', 'Scream (Calm Mind)', '{"ability":"Rattled","moves":["Calm Mind","Boomburst","Shadow Ball","Roost"],"item":"Leftovers","nature":"Bold","evs":{"hp":252,"atk":0,"def":156,"spa":0,"spd":0,"spe":100},"ivs":{"hp":31,"atk":0,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Poison"}'::JSONB),
  (983, 'gen9ou', 'Swords Dance', '{"ability":"Supreme Overlord","moves":["Swords Dance","Sucker Punch","Kowtow Cleave","Iron Head"],"item":"Leftovers","nature":"Adamant","evs":{"hp":0,"atk":252,"def":4,"spa":0,"spd":0,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Ghost"}'::JSONB),
  (984, 'gen9ou', 'Offensive Utility', '{"ability":"Protosynthesis","moves":["Headlong Rush","Ice Spinner","Rapid Spin","Close Combat"],"item":"Heavy-Duty Boots","nature":"Jolly","evs":{"hp":0,"atk":252,"def":4,"spa":0,"spd":0,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Steel"}'::JSONB),
  (985, 'gen9nu', 'Scream 2 (Booster Energy Calm Mind)', '{"ability":"Protosynthesis","moves":["Calm Mind","Boomburst","Fire Blast","Psychic Noise"],"item":"Booster Energy","nature":"Timid","evs":{"hp":40,"atk":0,"def":0,"spa":252,"spd":0,"spe":216},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Normal"}'::JSONB),
  (986, 'gen9zu', 'Offensive', '{"ability":"Protosynthesis","moves":["Crunch","Sucker Punch","Close Combat","Synthesis"],"item":"Heavy-Duty Boots","nature":"Adamant","evs":{"hp":0,"atk":252,"def":0,"spa":0,"spd":4,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Poison"}'::JSONB),
  (988, 'gen9uu', 'Pivot', '{"ability":"Protosynthesis","moves":["First Impression","Close Combat","Flare Blitz","U-turn"],"item":"Choice Scarf","nature":"Jolly","evs":{"hp":0,"atk":252,"def":0,"spa":0,"spd":4,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Fire"}'::JSONB),
  (989, 'gen9uu', 'Pivot', '{"ability":"Protosynthesis","moves":["Earth Power","Volt Switch","Power Gem","Spikes"],"item":"Heavy-Duty Boots","nature":"Timid","evs":{"hp":48,"atk":0,"def":0,"spa":208,"spd":0,"spe":252},"ivs":{"hp":31,"atk":0,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Ghost"}'::JSONB),
  (990, 'gen9ou', 'Utility', '{"ability":"Quark Drive","moves":["Stealth Rock","Earthquake","Knock Off","Rapid Spin"],"item":"Leftovers","nature":"Jolly","evs":{"hp":0,"atk":252,"def":0,"spa":0,"spd":4,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Ghost"}'::JSONB),
  (992, 'gen9ou', 'Swords Dance', '{"ability":"Quark Drive","moves":["Swords Dance","Drain Punch","Thunder Punch","Ice Punch"],"item":"Booster Energy","nature":"Adamant","evs":{"hp":0,"atk":252,"def":0,"spa":0,"spd":172,"spe":84},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Flying"}'::JSONB),
  (993, 'gen9uu', 'Booster Energy', '{"ability":"Quark Drive","moves":["Hurricane","Dark Pulse","Earth Power","Taunt"],"item":"Booster Energy","nature":"Timid","evs":{"hp":0,"atk":0,"def":0,"spa":252,"spd":4,"spe":252},"ivs":{"hp":31,"atk":0,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Ground"}'::JSONB),
  (994, 'gen9ou', 'Booster Energy', '{"ability":"Quark Drive","moves":["Fiery Dance","Sludge Wave","Dazzling Gleam","Substitute"],"item":"Booster Energy","nature":"Timid","evs":{"hp":0,"atk":0,"def":124,"spa":132,"spd":0,"spe":252},"ivs":{"hp":31,"atk":0,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Fairy"}'::JSONB),
  (1000, 'gen9ou', 'Offensive Nasty Plot', '{"ability":"Good as Gold","moves":["Nasty Plot","Shadow Ball","Make It Rain","Focus Blast"],"item":"Air Balloon","nature":"Timid","evs":{"hp":0,"atk":0,"def":0,"spa":252,"spd":4,"spe":252},"ivs":{"hp":31,"atk":0,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Fairy"}'::JSONB),
  (1001, 'gen9pu', 'Defensive', '{"ability":"Tablets of Ruin","moves":["Knock Off","Foul Play","Leech Seed","Protect"],"item":"Leftovers","nature":"Impish","evs":{"hp":252,"atk":0,"def":252,"spa":0,"spd":4,"spe":0},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Poison"}'::JSONB),
  (1003, 'gen9ou', 'Defensive Utility', '{"ability":"Vessel of Ruin","moves":["Stealth Rock","Earthquake","Ruination","Whirlwind"],"item":"Leftovers","nature":"Careful","evs":{"hp":252,"atk":0,"def":4,"spa":0,"spd":252,"spe":0},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Water"}'::JSONB),
  (1006, 'gen9ou', 'Mixed', '{"ability":"Quark Drive","moves":["Moonblast","Close Combat","Knock Off","Encore"],"item":"Booster Energy","nature":"Naive","evs":{"hp":0,"atk":4,"def":0,"spa":252,"spd":0,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Steel"}'::JSONB),
  (1009, 'gen9ou', 'Sun Wallbreaker', '{"ability":"Protosynthesis","moves":["Hydro Steam","Draco Meteor","Flamethrower","Dragon Pulse"],"item":"Choice Specs","nature":"Timid","evs":{"hp":12,"atk":0,"def":0,"spa":244,"spd":0,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Water"}'::JSONB),
  (1010, 'gen9uu', 'Swords Dance', '{"ability":"Quark Drive","moves":["Swords Dance","Leaf Blade","Psyblade","Close Combat"],"item":"Booster Energy","nature":"Jolly","evs":{"hp":96,"atk":160,"def":0,"spa":0,"spd":0,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Psychic"}'::JSONB),
  (1011, 'gen9pu', 'Physical Wall', '{"ability":"Sticky Hold","moves":["Recover","Growth","Giga Drain","Dragon Tail"],"item":"Eviolite","nature":"Bold","evs":{"hp":248,"atk":0,"def":252,"spa":0,"spd":8,"spe":0},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Steel"}'::JSONB),
  (1013, 'gen9uu', 'Calm Mind', '{"ability":"Heatproof","moves":["Calm Mind","Hex","Stun Spore","Strength Sap"],"item":"Leftovers","nature":"Bold","evs":{"hp":252,"atk":0,"def":160,"spa":0,"spd":0,"spe":96},"ivs":{"hp":31,"atk":0,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Poison"}'::JSONB),
  (1014, 'gen9ou', 'Assault Vest', '{"ability":"Toxic Chain","moves":["Drain Punch","Gunk Shot","Knock Off","Ice Punch"],"item":"Assault Vest","nature":"Adamant","evs":{"hp":240,"atk":252,"def":0,"spa":0,"spd":0,"spe":16},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Water"}'::JSONB),
  (1015, 'gen9nu', 'Choice Scarf', '{"ability":"Toxic Chain","moves":["Sludge Bomb","Psychic","U-turn","Trick"],"item":"Choice Scarf","nature":"Timid","evs":{"hp":0,"atk":0,"def":0,"spa":252,"spd":4,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Poison"}'::JSONB),
  (1016, 'gen9uu', 'Pivot', '{"ability":"Technician","moves":["Beat Up","Heat Wave","Roost","U-turn"],"item":"Heavy-Duty Boots","nature":"Bold","evs":{"hp":252,"atk":0,"def":240,"spa":0,"spd":16,"spe":0},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Water"}'::JSONB),
  (1017, 'gen9ou', 'Boots Pivot', '{"ability":"Defiant","moves":["Ivy Cudgel","Knock Off","U-turn","Encore"],"item":"Heavy-Duty Boots","nature":"Jolly","evs":{"hp":0,"atk":252,"def":4,"spa":0,"spd":0,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Grass"}'::JSONB),
  (1019, 'gen9uu', 'Offensive Nasty Plot', '{"ability":"Regenerator","moves":["Nasty Plot","Draco Meteor","Giga Drain","Earth Power"],"item":"Heavy-Duty Boots","nature":"Modest","evs":{"hp":252,"atk":0,"def":0,"spa":136,"spd":68,"spe":52},"ivs":{"hp":31,"atk":0,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Fairy"}'::JSONB),
  (1021, 'gen9ou', 'Calm Mind', '{"ability":"Protosynthesis","moves":["Calm Mind","Thunderclap","Dragon Pulse","Thunderbolt"],"item":"Booster Energy","nature":"Modest","evs":{"hp":0,"atk":0,"def":4,"spa":252,"spd":0,"spe":252},"ivs":{"hp":31,"atk":20,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Fairy"}'::JSONB),
  (1022, 'gen9ou', 'Swords Dance', '{"ability":"Quark Drive","moves":["Swords Dance","Mighty Cleave","Earthquake","Close Combat"],"item":"Booster Energy","nature":"Jolly","evs":{"hp":0,"atk":252,"def":0,"spa":0,"spd":4,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Fighting"}'::JSONB),
  (1023, 'gen9ou', 'Choice Specs', '{"ability":"Quark Drive","moves":["Tachyon Cutter","Psyshock","Volt Switch","Focus Blast"],"item":"Choice Specs","nature":"Timid","evs":{"hp":0,"atk":0,"def":0,"spa":252,"spd":4,"spe":252},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Steel"}'::JSONB),
  (1025, 'gen9ou', 'Pivot', '{"ability":"Poison Puppeteer","moves":["Parting Shot","Recover","Malignant Chain","Shadow Ball"],"item":"Heavy-Duty Boots","nature":"Bold","evs":{"hp":252,"atk":0,"def":228,"spa":0,"spd":0,"spe":28},"ivs":{"hp":31,"atk":0,"def":31,"spa":31,"spd":31,"spe":31},"teraType":"Ghost"}'::JSONB)
ON CONFLICT (pokemon_id, format, build_name) DO UPDATE SET
  build = EXCLUDED.build,
  enabled = TRUE;
-- END GENERATED SMOGON POOL

CREATE OR REPLACE FUNCTION public.build_random_vs_team(p_format TEXT DEFAULT NULL)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_snapshot JSONB;
  v_format TEXT;
BEGIN
  SELECT available.format INTO v_format
  FROM (
    SELECT builds.format
    FROM public.vs_competitive_builds builds
    WHERE builds.enabled
      AND (p_format IS NULL OR builds.format = p_format)
    GROUP BY builds.format
    HAVING COUNT(DISTINCT builds.pokemon_id) >= 6
    ORDER BY random()
    LIMIT 1
  ) available;

  IF v_format IS NULL THEN
    RAISE EXCEPTION 'The random competitive team pool is unavailable';
  END IF;

  SELECT jsonb_build_object(
    'teamId', 0,
    'name', 'Random Competitive · ' || UPPER(REPLACE(v_format, 'gen9', '')),
    'poolFormat', v_format,
    'members', jsonb_agg(
      jsonb_build_object(
        'pokemonId', rolled.pokemon_id,
        'species', pokemon.name,
        'types', pokemon.types,
        'position', rolled.position,
        'moves', rolled.build->'moves',
        'item', rolled.build->>'item',
        'ability', rolled.build->>'ability',
        'nature', rolled.build->>'nature',
        'evs', rolled.build->'evs',
        'ivs', rolled.build->'ivs',
        'level', 50,
        'isShiny', FALSE,
        'teraType', rolled.build->>'teraType'
      ) ORDER BY rolled.position
    )
  ) INTO v_snapshot
  FROM (
    SELECT selected.*, ROW_NUMBER() OVER (ORDER BY selected.roll)::INTEGER AS position
    FROM (
      SELECT builds.*, random() AS roll
      FROM public.vs_competitive_builds builds
      WHERE builds.enabled AND builds.format = v_format
      ORDER BY roll
      LIMIT 6
    ) selected
  ) rolled
  JOIN public.pokemon pokemon ON pokemon.id = rolled.pokemon_id;

  IF COALESCE(jsonb_array_length(
    CASE
      WHEN jsonb_typeof(v_snapshot->'members') = 'array' THEN v_snapshot->'members'
      ELSE '[]'::JSONB
    END
  ), 0) <> 6 THEN
    RAISE EXCEPTION 'The random competitive team pool is unavailable';
  END IF;

  RETURN v_snapshot;
END;
$$;

CREATE OR REPLACE FUNCTION public.create_random_vs_invite()
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
  v_user_id UUID := auth.uid();
  v_token TEXT;
  v_match public.vs_matches%ROWTYPE;
BEGIN
  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'Authentication required';
  END IF;

  v_token := encode(gen_random_bytes(24), 'hex');
  INSERT INTO public.vs_matches (host_user_id, invite_token_hash, host_team_snapshot)
  VALUES (
    v_user_id,
    encode(digest(v_token, 'sha256'), 'hex'),
    public.build_random_vs_team()
  )
  RETURNING * INTO v_match;

  RETURN jsonb_build_object(
    'match', to_jsonb(v_match) - 'invite_token_hash',
    'inviteToken', v_token
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.create_random_vs_friend_invite(p_friend_id UUID)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
  v_user_id UUID := auth.uid();
  v_host_name TEXT;
  v_result JSONB;
  v_match_id UUID;
  v_token TEXT;
BEGIN
  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'Authentication required';
  END IF;
  IF p_friend_id = v_user_id THEN
    RAISE EXCEPTION 'You cannot challenge yourself';
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM public.friendships friendship
    WHERE friendship.user_id_1 = LEAST(v_user_id, p_friend_id)
      AND friendship.user_id_2 = GREATEST(v_user_id, p_friend_id)
  ) THEN
    RAISE EXCEPTION 'You can only challenge an accepted friend';
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM public.user_presence presence
    WHERE presence.user_id = p_friend_id
      AND presence.last_seen_at >= NOW() - INTERVAL '90 seconds'
  ) THEN
    RAISE EXCEPTION 'That friend is no longer online';
  END IF;

  v_result := public.create_random_vs_invite();
  v_match_id := (v_result->'match'->>'id')::UUID;
  v_token := v_result->>'inviteToken';

  UPDATE public.vs_matches
  SET invited_user_id = p_friend_id, updated_at = NOW()
  WHERE id = v_match_id;
  v_result := jsonb_set(v_result, '{match,invited_user_id}', to_jsonb(p_friend_id), TRUE);

  SELECT COALESCE(
    profile.username,
    host_user.raw_user_meta_data->>'full_name',
    host_user.raw_user_meta_data->>'username',
    split_part(host_user.email, '@', 1),
    'A friend'
  ) INTO v_host_name
  FROM auth.users host_user
  LEFT JOIN public.profiles profile ON profile.id = host_user.id
  WHERE host_user.id = v_user_id;

  INSERT INTO public.notifications (user_id, type, title, message, url, data)
  VALUES (
    p_friend_id,
    'vs_invite',
    'Battle challenge',
    COALESCE(v_host_name, 'A friend') || ' challenged you to a VS battle',
    '/vs/invite/' || v_token,
    jsonb_build_object(
      'sender_id', v_user_id,
      'sender_name', COALESCE(v_host_name, 'A friend'),
      'match_id', v_match_id
    )
  );

  RETURN v_result;
END;
$$;

CREATE OR REPLACE FUNCTION public.accept_vs_invite_random(p_invite_token TEXT)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
  v_user_id UUID := auth.uid();
  v_match public.vs_matches%ROWTYPE;
BEGIN
  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'Authentication required';
  END IF;

  SELECT * INTO v_match
  FROM public.vs_matches
  WHERE invite_token_hash = encode(digest(p_invite_token, 'sha256'), 'hex')
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Invite not found';
  END IF;
  IF v_match.host_user_id = v_user_id THEN
    RAISE EXCEPTION 'The host cannot accept their own invite';
  END IF;
  IF v_match.invited_user_id IS NOT NULL AND v_match.invited_user_id <> v_user_id THEN
    RAISE EXCEPTION 'This invitation was sent to another trainer';
  END IF;
  IF v_match.status <> 'invited' OR v_match.guest_user_id IS NOT NULL THEN
    RAISE EXCEPTION 'Invite is no longer available';
  END IF;
  IF v_match.invite_expires_at <= NOW() THEN
    UPDATE public.vs_matches SET status = 'expired', updated_at = NOW() WHERE id = v_match.id;
    RAISE EXCEPTION 'Invite has expired';
  END IF;

  UPDATE public.vs_matches
  SET guest_user_id = v_user_id,
      guest_team_snapshot = public.build_random_vs_team(
        CASE
          WHEN v_match.host_team_snapshot->>'teamId' = '0'
            THEN v_match.host_team_snapshot->>'poolFormat'
          ELSE NULL
        END
      ),
      status = 'lobby',
      updated_at = NOW()
  WHERE id = v_match.id
  RETURNING * INTO v_match;

  RETURN to_jsonb(v_match) - 'invite_token_hash';
END;
$$;

REVOKE ALL ON FUNCTION public.build_random_vs_team(TEXT) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.create_random_vs_invite() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.create_random_vs_friend_invite(UUID) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.accept_vs_invite_random(TEXT) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION public.create_random_vs_invite() TO authenticated;
GRANT EXECUTE ON FUNCTION public.create_random_vs_friend_invite(UUID) TO authenticated;
GRANT EXECUTE ON FUNCTION public.accept_vs_invite_random(TEXT) TO authenticated;
